### ISSUE TITLE
Loading external assets

### ISSUE THREAD

**Issue by mcmonkey4eva** [SiliconStudio/paradox#103]
Is it possible to load an external asset from, EG, a C# Stream object (Which could be used for locally stored data, or a FileStream, or a thousand other loading methods)?

The content pipeline feels restrictive to me, particularly if I want the game to be easily modable.

EDIT: This is now a feature request for direct loading assets from files (or probably any give `Stream` object) without the need for it to be in a 'raw assets' folder or the like. This should be possible in theory on all platforms, even windows store / phone apps are capable of having their own little internal file system that can be accessed.

**Comment by xoofx** [comment]
@mcmonkey4eva This feature will be added in the september release.

**Comment by Benlitz** [comment]
This can be done by using the import asset menu and select the RawAssetImporter.
