### ISSUE TITLE
Problems building Paradox.sln [beta04]

### ISSUE THREAD

**Issue by gitfool** [SiliconStudio/paradox#116]
Some test projects don't build:

* SiliconStudio.Paradox.Assets.Tests
* SiliconStudio.Paradox.Engine.Tests.Windows
* SiliconStudio.Paradox.Graphics.Tests.Windows

I'm using the latest source as at commit [b47b609](https://github.com/SiliconStudio/paradox/commit/b47b6095384c4838c1e64e4fcd86e56a1c8745a3). The build is sufficiently complex that I can't make head or tail of it. ;)

[BuildLog.txt.zip | uploaded via ZenHub](https://files.zenhub.io/54757e8ee11065d4131598d2)

**Comment by boriscallens** [comment]
Is this still the case?
Yesterday I forked SHA: 1588c99fddc1d730706d9d11f769e7f63fc4b1a3 and it built without problems in VS2013. If fixed maybe @xen2 can tag this one as fixed?

**Comment by xen2** [comment]
Yes it can be closed, thanks!
