### ISSUE TITLE
Problems building ParadoxSamples.sln [beta04]

### ISSUE THREAD

**Issue by gitfool** [SiliconStudio/paradox#117]
This is fairly straight forward. All the samples using `SpriteBatch.MeasureString` are currently broken due to the newly required `targetSize` parameter.

This begs the question; what should this be? If it's usually something like `new Vector2(GraphicsDevice.BackBuffer.Width, GraphicsDevice.BackBuffer.Height)` then it might be better to make that the default value, with a `Vector2? targetSize = null` (or similar), to make the API more lightweight / user friendly.

This crossed my mind when thinking about having to patch every single call site in the samples to use the exact same long winded parameter value. ;)

**Comment by boriscallens** [comment]
Think this should have status Fixed.
@xen2 Should the 'fixes' part be capitalized or put at the start of your message to automagically put the Fixed state on the #mentioned issues?
https://guides.github.com/features/issues/#notifications

**Comment by xenux** [comment]
Yes this issue should be closed.
By the way I added the change proposed by gitfool too.
