### ISSUE TITLE
Exception adding and assigning FBX asset to entity

### ISSUE THREAD

**Issue by kerams** [SiliconStudio/paradox#122]
Importing a simple plane from Blender, checking the options to create the corresponding material and model, but not entity. The model's preview shows that something-is-broken picture and when I try to assign it to an existing entity, I get the following exception:

    Paradox Version: 1.0.0-beta06
    GameStudio Version: 4
    Error Message: Unexpected exception
    User: [snip]
    Current Directory: C:\Program Files (x86)\Paradox\GamePackages\Paradox.1.0.0-beta06\Bin\Windows-Direct3D11
    OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
    Command Line Args: 
    Exception type: NullReferenceException
    Exception message: Object reference not set to an instance of an object.
    StackTrace:    v SiliconStudio.Paradox.Engine.MeshProcessor.Draw(GameTime time)
       v SiliconStudio.Paradox.EntityModel.EntitySystem.Draw(GameTime gameTime)
       v SiliconStudio.Paradox.Games.GameSystemCollection.Draw(GameTime gameTime)
       v SiliconStudio.Paradox.Games.GameBase.Draw(GameTime gameTime)
       v SiliconStudio.Paradox.Games.GameBase.DrawFrame()
       v SiliconStudio.Paradox.Games.GameBase.Tick()
       v SiliconStudio.Paradox.Games.GamePlatform.Tick()
       v SiliconStudio.Paradox.Games.GamePlatform.OnRunCallback()
       v SiliconStudio.Paradox.Games.GameWindowDesktop.<>c__DisplayClass2.<Run>b__0()
       v SiliconStudio.Paradox.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
       v SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
       v SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
       v SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
       v SiliconStudio.Paradox.GameStudio.ParadoxViewService.ParadoxUIThread(Object projectSession)
       v SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass4.<Wrap>b__3(Object obj)

What is strange is the fact that if I then reopen the studio and project, previews work fine and upon running the game I can see the asset correctly.

**Comment by Benlitz** [comment]
Hi,

This part has completely changed since the version 1.0 of Paradox, I guess we can close this issue (Entities do not exist anymore). If you still have import issues with the latest version, feel free to create a new issue.
