### ISSUE TITLE
Drawing fonts ignores alpha value

### ISSUE THREAD

**Issue by axefrog** [SiliconStudio/paradox#149]
```c#
var color = Color.CornflowerBlue;
var alpha = .2f;
color = new Color(color.R, color.G, color.B, (byte)(255*alpha));
_batch.DrawString(font, text, fontSize, new Vector2(x, y), color);
```

The alpha value is always ignored and the font is drawn with full opacity.

Note that it is very difficult to achieve interesting text effects without the ability to render with variable opacity.

**Comment by axefrog** [comment]
Further investigation suggests it sort of works, but not entirely as expected. In the following images, the bracketed values at the end of each line indicate the R,G,B,A values taken from the `Color` object used to render the line:

Black text appears to render transparency correctly:
![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/08415955-af4d-403d-9b79-7e1501781497/2015-01-10_1034.png)

White text ignores transparency completely:
![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/c9eca531-cef4-47ae-b74e-bdd5f30c4ddd/2015-01-10_1036.png)

Red text on black also not showing transparency:
![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/f63b8c53-55fc-4e4d-9224-2dc28609d517/2015-01-10_1038.png)

Red text on white appears to work correctly:
![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/a9c32fa7-e609-48bf-9921-ed9ac9dce550/2015-01-10_1040.png)

**Comment by xoofx** [comment]
The person in charge of the font rendering will be back later next week. I suspect this is related to premultiplied alpha, have you tried by premultiplying rgb color by alpha component? (multiply each r,g,b by 0.2 in your case)

**Comment by axefrog** [comment]
I don't really understand what premultiplied alpha is all about. I've tried checking "No premultiplied alpha" in the asset properties, but it doesn't seem to have any effect. What's the significance of the 0.2 multiplier you're suggesting?

**Comment by xoofx** [comment]
In the sample above, you alpha color is 0.2, so in your code a premultiplied color would be `color = new Color((byte)(color.R * alpha), (byte)(color.G * alpha), (byte)(color.B * alpha), (byte)(255*alpha));` I haven't checked the code behind, so it might not work, just a suggestion.

**Comment by axefrog** [comment]
Oh whoops, I didn't notice my code snippet had 0.2f for the alpha.
Thanks, your suggestion worked perfectly! Clearly my "bug" report is down to an overly-simplistic of understanding of this stuff...

**Comment by xen2** [comment]
Just making sure, is the issue resolved or is there still something left to fix?
If not I will close it.

**Comment by axefrog** [comment]
I guess it's closed. It all depends on whether you think colors should be able to be specified without having to premultiply the alpha against each color channel.

**Comment by xoofx** [comment]
By default SpriteBatch is using a pre-multiplied alpha blend state for textures, so the color is also following this default behavior.
