### ISSUE TITLE
Minor mesh rotation bug in the terrain sample

### ISSUE THREAD

**Issue by axefrog** [SiliconStudio/paradox#153]
In the Paradox sample that generates procedural terrain, the mesh starts off by rotating slowly, but very quickly starts rotating faster and faster, meaning you only have a very limited window of time to fiddle with the controls before the terrain is spinning too fast to easily observe properly. If you leave it running for a little while, the terrain eventually spins so fast that you can't even see it properly.

**Comment by Twelvy** [comment]
Hi,

Suprinsingly I noticed the same behavior this morning. It will be fixed in next release. If you want to fix it by yourself, replace the following line in UpdateInput method (in SimpleTerrainGame.cs):
```
rotY += (float)(2 * Math.PI * (UpdateTime.Total.TotalMilliseconds % 20000000) / 20000000);
```
by
```
rotY += (float)(2 * Math.PI * (UpdateTime.Elapsed.TotalMilliseconds % 20000) / 20000);
```
