### ISSUE TITLE
SpriteBatch.Begin invalid summary can cause confusion

### ISSUE THREAD

**Issue by Discosultan** [SiliconStudio/paradox#155]
Hi!

SpriteBatch.Begin (including overloads) states in the summary that if no DepthStencilState is specified, DepthStencilState.None is used ([see here](https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Graphics/SpriteBatch.cs#L89)). In reality, DepthStencilStates.Default is used ([see here](https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Graphics/BatchBase.cs#L197)).

This can easily cause confusion where drawn objects are culled by depth test while the user expects depth test to be disabled.

**Comment by xenux** [comment]
Thanks for the report. I just fixed the comments. It will be included in the next release.

**Comment by Discosultan** [comment]
Seems to be fixed, thank you!
