### ISSUE TITLE
"Frustum" is spelled as "Frustrum"

### ISSUE THREAD

**Issue by HugoPeters** [SiliconStudio/paradox#156]
The method to add Frustum Culling to a ModelRenderer is called "AddDefaultFrust**r**umCulling", as well as in the documentation.

From Wikipedia:

"The English word is often misspelled as frustrum, a different Latin word cognate to the English word "frustrate"."

**Comment by xenux** [comment]
Thanks for the report. I fixed the typo (it was present in other places too). I will be included in next release.
