### ISSUE TITLE
Cannot find custom tool 'ParadoxShaderKeyGenerator'

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/paradox#159]
This hasn't been a problem for me in the past, and cs files have been either auto-generated from .pdxsl files or else i've been able to right click in Visual Studio and select 'run custom tool' to fix things up. But today when i was just running through the process of adding a test shader the cs file was not generated and when i select 'run custom tool' I get the error message :

Cannot find custom tool 'ParadoxShaderKeyGenerator'

I have a new Windows installation as of a few days ago, still using Windows 8.1, but i did change from VS2013Pro to VS2013Community.

**Comment by xen2** [comment]
You can try reinstalling the VS Package.
It is located at %SiliconStudioParadoxDir%\GamePackages\Paradox.1.0.0-beta06\Bin\Windows-Direct3D11\SiliconStudio.Paradox.vsix

**Comment by Gavin-Williams** [comment]
I received the following error :

...
Requires a version of .net framework that is not installed

So i used clrver in a VS command prompt which shows v4.0.30319 installed.
I ran the Microsoft .NET Framework 4.5.2 installer, and it says 4.5.2 or later update is already installed.

**Comment by Gavin-Williams** [comment]
A follow up: there seemed to be something out of step with my installs/updates .. restart was required. 
After that I was able to install .net framework 4.5...4.52 pack. then the VSIX Installer gave the following 'warning':

This extension does not contain a digital signature
This extension did not specify licence terms in its manifest that are readable by VSIX Installer.

It then failed.

**Comment by Gavin-Williams** [comment]
Closing this issue, after many hours of painful checking and re-installation, my conclusion is that Visual Studio 2015 (with .net 2.6) corrupted my .net installation. No re-installation of the .net versions, nor the .net repair tool could fix it. I had to completely reinstall Windows to fix .net.
