### ISSUE TITLE
Launcher downloading percentage bug.

### ISSUE THREAD

**Issue by TommasoScalici** [SiliconStudio/paradox#165]
When downloading new versions the download percentage of the launcher restart from 0 and then stuck to some random value.
![launcher bug](https://cloud.githubusercontent.com/assets/6296587/6038992/8a288afa-ac62-11e4-908d-c1450f89d7e0.png)

**Comment by Benlitz** [comment]
Sorry about that, it seems that the launcher sometimes got its percentage count reset during the download. It might be a bit confusing but things should work well anyway.

If you press *Sì*, does it start installing the new version?
If no, if you restart Paradox from the startup menu, does it start installing the new version at this time?

We will update the launcher in a future release.

**Comment by TommasoScalici** [comment]
Yes, all the installing process works as expected, it's just a "visual bug" ;)

**Comment by Benlitz** [comment]
Ok, thanks for reporting!

**Comment by xoofx** [comment]
I tried in the past to fix this, but as we are using nuget, it is reporting a wrong download progress and haven't been able to dig more into why.
