### ISSUE TITLE
Opening 1.06 project crashed game studio.

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/paradox#166]
Here is the debug output..

https://gist.github.com/3b13032cba9cc0e105f2.git
or 
https://gist.github.com/Gavin-Williams/3b13032cba9cc0e105f2

**Comment by Benlitz** [comment]
Note: might be related to https://github.com/SiliconStudio/paradox/issues/133

**Comment by Benlitz** [comment]
I'm closing this issue since it's quite old and the related part has completely changed in the recent versions
