### ISSUE TITLE
Paradox.pdxpkg file in wrong location

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/paradox#167]
I'm getting the following error :

Error 1 Error while loading default package from [C:/Users/Gavin/AppData/Local/Programs/Paradox\Paradox.pdxpkg]: []: Error: Package file [C:\Users\Gavin\AppData\Local\Programs\Paradox\Paradox.pdxpkg] was not found

the actual location is :
C:\Users\Gavin\AppData\Local\Programs\Paradox\GamePackages\Paradox.1.0.0-beta09

I assume that the \Paradox\ is sys defined location, anyway, somethings up.

**Comment by Benlitz** [comment]
Did you create a new project or were you trying to open an existing project that you started with a previous version?

**Comment by Gavin-Williams** [comment]
Existing project, I'll create a new one later tonight to fix it up. Thought i should still mark this as an issue even though that's the obvious thing to do.

**Comment by Benlitz** [comment]
Yes, of course that is something we must investigate.
Thanks for reporting

**Comment by Gavin-Williams** [comment]
As i'm fixing up my project, I'm getting the following error (59 errors all the same)

Error	59	Error while loading default package from [C:/Users/Gavin/AppData/Local/Programs/Paradox\Paradox.pdxpkg]: []: Error: Package file [C:\Users\Gavin\AppData\Local\Programs\Paradox\Paradox.pdxpkg] was not found

**Comment by xoofx** [comment]
Could you post what is the content of the file "$(PARADOX_DIR)\Targets\SiliconStudio.Common.targets" ?  This file is updated by the Paradox Launcher. Also what do you have under GamePackages?

**Comment by Toasterthegamer** [comment]
I have the same issue here is my targets file:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="CheckPackages">
  <PropertyGroup>
    <SiliconStudioPackageParadoxVersionSaved>$(SiliconStudioPackageParadoxVersion)</SiliconStudioPackageParadoxVersionSaved>
    <SiliconStudioPackageParadoxVersionInvalid Condition="'$(SiliconStudioPackageParadoxVersion)' == '' or !Exists('$(MSBuildThisFileDirectory)..\GamePackages\Paradox.$(SiliconStudioPackageParadoxVersion)\Targets\Paradox.targets')">true</SiliconStudioPackageParadoxVersionInvalid>
    <SiliconStudioPackageParadoxVersion Condition="'$(SiliconStudioPackageParadoxVersionInvalid)' == 'true'">1.0.0-beta09</SiliconStudioPackageParadoxVersion>
  </PropertyGroup>
  <Target Name="CheckPackages">
    <Message Condition="'$(SiliconStudioPackageParadoxVersionInvalid)' == 'true'" Text="Package Paradox with version [$(SiliconStudioPackageParadoxVersionSaved)] not found. Use version $(SiliconStudioPackageParadoxVersion) instead" />
  </Target>
  <Import Project="$(MSBuildThisFileDirectory)..\GamePackages\Paradox.$(SiliconStudioPackageParadoxVersion)\Targets\Paradox.targets" Condition="Exists('$(MSBuildThisFileDirectory)..\GamePackages\Paradox.$(SiliconStudioPackageParadoxVersion)\Targets\Paradox.targets')" />
</Project>

**Comment by xen2** [comment]
Can you try deleting the .suo of this solution? (sometimes things are not refreshed properly by visual studio MSBuild cache)

**Comment by xen2** [comment]
Also, if you could enable MSBuild Diagnostic logging, rebuild, and send us the log file, that would be really helpful!

**Comment by xen2** [comment]
Also, do you have this error in Visual  Studio when building assets, or when opening game with Game Studio?

**Comment by Toasterthegamer** [comment]
I deleted the suo file and that fixed the issue for me, maybe that is something paradox game studio can do when opening a project after an update?

**Comment by Gavin-Williams** [comment]
Sorry, I haven't checked in for a few days, and I have another issue which is getting in the way right now, so I'll have to work that out before I can respond properly to the above requests.

**Comment by Gavin-Williams** [comment]
So I don't have the issue anymore either. I think it's kind of a false error. It was a visual studio error message.

**Comment by xen2** [comment]
> I deleted the suo file and that fixed the issue for me, maybe that is something paradox game studio can do when opening a project after an update?

Paradox VSPackage is supposed to do that, not sure why it didn't work.
