### ISSUE TITLE
FrustumCulling(beta09)

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#168]
Only entity with translation (0,0,0) is culling properly. Something wrong with world matrix of the Mesh. (renderMesh.Mesh.Parameters.Get(TransformationKeys.World, out mat1)).
In beta06 entity frustumculling is working properly.

**Comment by boriscallens** [comment]
Wasn't this fixed in #237?

**Comment by xenux** [comment]
Thanks for the catch
