### ISSUE TITLE
SpriteBatch with custom effect stopped working [beta08/09]

### ISSUE THREAD

**Issue by gitfool** [SiliconStudio/paradox#170]
I'm rendering a SpriteBatch with a custom effect. This was working prior to merging the beta08 source (beta09 Paradox Studio). I could be doing something wrong, so to illustrate the problem I hacked the Custom Effect Sample to use a SpriteBatch instead of a PrimitiveQuad (similar to issue #30).

[CustomEffect.zip | uploaded via ZenHub](https://files.zenhub.io/54d3273d1a9f2bbc5208bf08)

Am I doing something wrong or not? ;)

**Comment by gitfool** [comment]
Same problem on Android (and presumably iOS, but I've been unable to deploy to my iPad for a quick test - a Xamarin issue).

PrimitiveQuad+Effect works, whereas SpriteBatch+Effect does not.

**Comment by xen2** [comment]
Thanks for the report.

Seems like we were caching vertex array objects (aka input signature + input layout) too aggressively.

**Comment by xen2** [comment]
This will be fixed in next release.
Also, I have made SpriteBatch.Parameters public due to the removal of Effect.Parameters (http://answers.paradox3d.net/questions/1133/effectparameters-removed-beta09.html)
