### ISSUE TITLE
Some engine provided vertex types do not implement IVertex interface.

### ISSUE THREAD

**Issue by Discosultan** [SiliconStudio/paradox#185]
* [VertexPosition2](https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Graphics/VertexPosition2.cs#L14)
* [VertexPositionColorTexture](https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Graphics/VertexPositionColorTexture.cs#L13)
* [VertexPositionColorTextureSwizzle](https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Graphics/VertexPositionColorTextureSwizzle.cs#L14)

I presume they are meant to follow the same guidelines as the rest of the vertex types.

**Comment by boriscallens** [comment]
Everything but for VertexPosition2 seemes fixed in f5c45f5855842d0fe0942032dc08230ce9bb034d

**Comment by xenux** [comment]
Thanks for the report. I will be fixed in next release.

**Comment by boriscallens** [comment]
:+1:
