### ISSUE TITLE
Alignment(s) have no effect on UIElements

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/paradox#188]
If I set HorizontalAlignment and VerticalAlignment each to Center, it has no effect and the control is rendered at 0,0.

**Comment by xenux** [comment]
Horizontal/VerticalAlignment have effect only if the size provided to the element is bigger than the size needed by the element. Most of the layouts provides to the children only the size they need so H/VAlignments have no effects. What is the parent layout you included your element into? 

(Note: it is recursive)

**Comment by Gavin-Williams** [comment]
I have a Canvas as my Scene (1920x1080). And I have a confirmation dialog which i want in the center of the screen. I can position it with SetCanvasAbsolutePosition() but using Alignment, I would expect it to be positioned correctly for me.

    screenCanvas.HorizontalAlignment = HorizontalAlignment.Stretch;
    screenCanvas.VerticalAlignment = VerticalAlignment.Stretch;
    ...
    jumpDownPitConfirmation = new Canvas()
    {
        HorizontalAlignment = HorizontalAlignment.Center,
        VerticalAlignment = VerticalAlignment.Center,
        Size = new Vector3(360, 120, 0),
        Visibility = SiliconStudio.Paradox.UI.Visibility.Collapsed,
        Opacity = 1f
    };
    screenCanvas.Children.Add(jumpDownPitConfirmation);

**Comment by xenux** [comment]
If you want to position an element at the center of a canvas use the Canvas.RelativeSizePropertyKey with value 0.5f. 
Horizontal/VerticalAlignment take effect only when the parent layout provides the child with a bigger size than needed. For example in a grid where the column/row size is determined by the biggest element (all smaller elements have to position themselves in the too spacious provided space).
