### ISSUE TITLE
cannot step into paradox assemblies

### ISSUE THREAD

**Issue by jmkinzer** [SiliconStudio/paradox#193]
Using a solution generated via the game studio (and using the binaries not a source built) I'm unable when debugging to step into any of the paradox assemblies. I noticed the pdbs are not copied into the solution but manually copying them in did not seem to help in any case.

**Comment by gitfool** [comment]
There are no symbol files included with the binary release, so if you want to step into the Paradox source then you should [build](https://github.com/SiliconStudio/paradox/blob/master/doc/GettingStarted.md) it first. Leave the environment variable pointing to your custom build, then build and debug your project.

**Comment by jmkinzer** [comment]
OK, my bad. Thanks!
