### ISSUE TITLE
Vertex/Index buffer memory leak.

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/paradox#195]
I seem to be experiencing a memory leak when using vertex and index buffers. Example code:

                // Create the vertex buffer.
                ParadoxGraphics.Buffer VertexBuffer = ParadoxGraphics.Buffer.Vertex.New<Meshes.VertexNormalTexture>(context.GraphicsDevice, primitiveList.Length);
                VertexBuffer.SetData<Meshes.VertexNormalTexture>(primitiveList);

                // Create the index buffer.
                ParadoxGraphics.Buffer IndexBuffer = ParadoxGraphics.Buffer.New<int>(context.GraphicsDevice, indices.Length, BufferFlags.IndexBuffer);
                IndexBuffer.SetData<short>(indices);

                VertexArrayObject vao = VertexArrayObject.New(context.GraphicsDevice, new IndexBufferBinding(IndexBuffer, false, indices.Length), new[] { new VertexBufferBinding(VertexBuffer, Meshes.VertexNormalTexture.VertexDeclaration, primitiveList.Length) });

                // Drawing code
                // Apply effect.
                Engine.MainEffect.Apply(context.Parameters);

                context.GraphicsDevice.SetVertexArrayObject(vao);
                context.GraphicsDevice.DrawIndexed(PrimitiveType.LineList, indices.Length, 0, 0);

                // Dispose code
                primitiveList = null;
                indices = null;
                VertexBuffer.Dispose();
                IndexBuffer.Dispose();
                vao.Dispose();

I look at my memory and I can watch both the GPU and CPU memory grow as I add more objects to my scene, but when I remove them they do not get disposed of correctly and I run out of memory eventually.

I mainly use DrawIndexed to draw bounding boxes for debugging purposes and I'm not sure if this issue persists with the entity system as well, but I'll try to test that.

**Comment by Toasterthegamer** [comment]
I tested this with the entity system as well. Memory increases as you remove/add entities. Even though the total number of entities and the size of the entities data does not change.

**Comment by jwollen** [comment]
Do you still have this issue? I can't seem to reproduce it, neither with buffers nor entities. If so, could you provide a sample project?

**Comment by Toasterthegamer** [comment]
Perhaps I am disposing of the entity incorrectly, but here is a modified Animated Model sample that shows the error. 
https://app.box.com/s/kgy5q23dkngtjxm9j2faoh6uuh5l4p1w

**Comment by jwollen** [comment]
Cloning is necessary, otherwise you would be trying to readd the same entity.

The problem in the sample appears to be cloning the entity, including the ScriptComponent that's doing the cloning (thus growing the number of entities exponentially). Try moving the actual cloning script into a separate entity.

**Comment by Toasterthegamer** [comment]
Ah right that makes sense I didn't even think about that, I am still seeing a memory leak though. I let the app run for a while and it went from 175mb's to 943mb's. Do the individual components of an entity need to be disposed as well?

You'll have to let the new sample run a while to see the increase in memory, I think mine was running 20 minutes to get to 943mb's. Here is a link to download the new sample project with the changes(same link as before new files):
https://app.box.com/s/kgy5q23dkngtjxm9j2faoh6uuh5l4p1w

**Comment by jwollen** [comment]
This happens because there is no stopping condition for the RotateEntity script. So the scripts keep running even after their entities get removed. You could check for removal like this:
```
while (Game.IsRunning && Entity.Transform.Parent != null)
{
    ...
}
```
Readding the entity would also restart the script.
