### ISSUE TITLE
Sample error with Material

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/paradox#197]
I get the following error when trying to assign a mixin for a materials albedoDiffuse when using the deferred rendering system:

```
error X3013: 'Sample': no matching 2 parameter intrinsic method
Possible intrinsic methods are:
Texture2DArray<float4>.Sample(SamplerState, float3|half3|min10float3|min16float3)
Texture2DArray<float4>.Sample(SamplerState, float3|half3|min10float3|min16float3, int2)
Texture2DArray<float4>.Sample(SamplerState, float3|half3|min10float3|min16float3, int2, float1|half1|min10float1|min16float1)
Texture2DArray<float4>.Sample(SamplerState, float3|half3|min10float3|min16float3, int2, float1|half1|min10float1|min16float1, out uint status)
```

The shader:
```
class MultiTextured : ComputeColor
{
	SamplerState MeshTextureSampler
	{
		Filter = MIN_MAG_MIP_LINEAR;
		AddressU = Wrap;
		AddressV = Wrap;
        AddressW = Clamp;
        MaxAnisotropy = 16;
	};

	stage Texture2DArray Textures;

	stage stream float3 TexCoord : TEXCOORD0;

    compose AmbientOcclusion AO;

	override float4 Compute()
    {
        float4 Color = AO.Compute();

		Color *= Textures.Sample(MeshTextureSampler, streams.TexCoord);

		return float4(Color.rgb, 1);
	}
};
```

I took a look at the shader itself and I don't see anything wrong. Here is the line that the error links to:
```
    Color *= Textures_id84.Sample(MeshTextureSampler_id83, streams.TexCoord_id76);
```

**Comment by jwollen** [comment]
A variable with `TEXCOORD0` may have been previously declared in your effect as `float2`, e.g. by mixing in something that derives from `Texturing`. These variables are then merged and yours is loosing. This probably deserve a compiler error.

Try changing the semantic. You can also make it configurable, like in [ComputeColorTexture](https://github.com/SiliconStudio/paradox/blob/537b0ea9f600b3f5fe66386d373e5feb0a18f6c0/sources/shaders/ComputeColor/ComputeColorTexture.pdxsl).

**Comment by Toasterthegamer** [comment]
This was exactly the issue! Once I changed this it works, the error returned was confusing compared to what the actual issue. Can this be changed in the future?

**Comment by jwollen** [comment]
This will output a proper error message in the next release.
