### ISSUE TITLE
Website contact form

### ISSUE THREAD

**Issue by Kryptos-FR** [SiliconStudio/paradox#199]
Summary:
In the website, the [contact form](http://paradox3d.net/contact) does not work.
It shows a message stating "Notice SMTP connect failed".

Steps to reproduce:
Go to the contact form page (using the link provided above).
Fill in all the fields.
Click on "Send Email".

**Comment by xoofx** [comment]
Thank you for the report. We will fix this asap.

**Comment by h-sao** [comment]
Sorry for being late.
We fixed it.
