### ISSUE TITLE
Github activity

### ISSUE THREAD

**Issue by boriscallens** [SiliconStudio/paradox#200]
I have been watching the github repository of paradox since the 1.0.0-beta10 commit on 12 february.
Since then there has been very little activity despite the GDC announcement.

Is the project on hold?
Is there a different branch then Main I should be watching?
Is development done on a private (separate) source control system?

Really looking forward to future commits and hoping Paradox can become a worthy game IDE that encourages clean code.

**Comment by xen2** [comment]
Most of our work happen on a separate git repository, please rest assured that lot of commits are happening every day on Paradox.

We have been quite busy with GDC, and trying to polish all that recent work for next release.
More details here: http://paradox3d.net/blog/gdc-2015-scene-editor-new-rendering

Hope you will like it!

**Comment by boriscallens** [comment]
Good to hear and thanks for the very speedy response :)

It was because the blog mentioned a scene editor I was curious about how state would be managed in Paradox. I was eager to see if the whole scene state management would be handled better/differently then how Unity handles it (frequent serialize/deserialize, hijack constructors, have a completely different event handling for editor/game mode).

Is the separate repository private or can we be lurkers somehow ?
