### ISSUE TITLE
Right, Left, Up, Down, etc for Vector and Matrix classes.

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/paradox#201]
This is just a feature request it would be nice to have these as it would make working with matrices and vectors easier sometimes!

**Comment by xoofx** [comment]
We have added this to the Matrix struct and should be part of next release.

**Comment by Toasterthegamer** [comment]
Awesome great news!

**Comment by HugoPeters** [comment]
Thanks a lot, was looking for this as well!
