### ISSUE TITLE
Setting graphicsdevice.parameters disables the entity system's transforms.

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/paradox#202]
I have a few bounding boxes that I am drawing manually and I set three shader parameters using:

            context.GraphicsDevice.Parameters[TransformationKeys.World] = Matrix.Identity;
            context.GraphicsDevice.Parameters[TransformationKeys.View] = CurrentCamera.View;
            context.GraphicsDevice.Parameters[TransformationKeys.Projection] = CurrentCamera.Projection;

Which breaks the entity system's transformations. If I use context.Parameters instead it works fine. I'm not sure if this is by design or if this is a bug? Not really a huge bug if it is.

Thanks!

**Comment by xoofx** [comment]
This is by design. The `GraphicsDevice.Parameters` are always overriding all parameters defined. Usually you should not have to modify parameters at the GraphicsDevice level but directly when you are drawing things with an effect (an effect takes a ParameterCollection).
