### ISSUE TITLE
Character Set UI bug

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#210]
1) Start Paradox Studio, select any project with sprite font
2) Select sprite font asset
3) Click to Character Set text box in Property Grid, but don't type anything
4) Select something else to loose focus

Looks like if you do that Character Set is is not null anymore, string is empty. Project is not possible to build or even save. I didn't find any workaround.

**Comment by Benlitz** [comment]
Indeed. I've fixed this issue on our development branch so it should be ok for the next release.

Unfortunately there is no workaround for this issue, except maybe deleting the asset and recreating it.
