### ISSUE TITLE
Inconsistent culture in NumericTextBox's value coercion

### ISSUE THREAD

**Issue by jwollen** [SiliconStudio/paradox#211]
`NumericTextBox` [formats values with invariant culture](https://github.com/SiliconStudio/paradox/blob/f5c45f5855842d0fe0942032dc08230ce9bb034d/sources/common/presentation/SiliconStudio.Presentation/Controls/NumericTextBox.cs#L574) while parsing with current culture.

Either formatting with current culture, or trying first to parse with invariant culture solves the issue. Also, to allow both to be input, the first parse should probably ignore the `NumberGroupSeparator` if it matches the second one's `NumberDecimalSeparator`.

Related to [this question](http://forums.paradox3d.net/t/does-anyone-have-the-same-problem/211).

**Comment by Benlitz** [comment]
This issue has been fixed on our development branch and will be integrated in the next release
