### ISSUE TITLE
The new scene editor keep loading 

### ISSUE THREAD

**Issue by geeksan** [SiliconStudio/paradox#215]
I've donwloaded the new release of Paradox game engine (1.1), since that upgrade I can't access anything inside the game engine, the scene editor keeps loading over and over but does not  display anything . 
Apologize for my poor English

**Comment by Benlitz** [comment]
Hi,
I have a few questions to ask to understand better the problem:
- is the scene editor frozen or is it still responsive?
- what is displayed inside the scene editor? Is it the loading message or is it something else?
- what kind of project are you trying to load? (a sample or an empty game?)
- what GPU do you have?
- are you on a x64 version of Windows? Which version?

Could you try to wait about 1 minute to see if it does not complete loading, just in case it is an issue with the shader compilation?

Thanks!

**Comment by soloparatolos** [comment]
Hi, I have the same problem.

In my case the thing is:

-The scene is still reponsive, I can compile the proyect and run the proyects.
- Inside the scene and the resources windows only appear loading bars, asking to wait( I waited about 3 hours).
-This happens with all the proyects I try to load, the new and the sample ones.
- I have and ati hd5570 1gb and a windows7 64bit sp1.

I hope the information is useful.

**Comment by geeksan** [comment]
-The scene is still responsive
-Everything is loading in the scene editor
-I tried all the different projects many times
-I am on x64 , window 8.1
-AMD READON HD7520G 2gb 
I waited for hours

**Comment by Benlitz** [comment]
Ok, thank you for your answers. This seems to be a serious issue and we will investigate it quickly.

**Comment by Benlitz** [comment]
Could you please check in the debug window (it can be open from Help menu > Debug Window or with Ctrl+Shift+D), if there's anything displayed in the "Scene" tab? An exception, some errors or warnings?

Note: this tab will appear only after loading a project

![DebugWindow](http://i.imgur.com/mXUMTJd.png)

**Comment by soloparatolos** [comment]
Hi again,

My Debug window is completely empty in all tabs except the Quantum log, that looks normal(no errors).

**Comment by Benlitz** [comment]
Ok, thanks again. We will investigate this issue

**Comment by xen2** [comment]
It was an issue on single-core and dual-core CPU. This should be fixed in next release.
