### ISSUE TITLE
Shaders causing visual studio to lock up.

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/paradox#216]
I'm attempting to edit a shader I have and I think because I copied some GLSL code into(trying to convert to HLSL) it causes the error detector to get stuck in a loop and locks up visual studio.

Specifically something like: float test = mod(1, 10) causes a lockup.

**Comment by jwollen** [comment]
Could you post the full shader, or a minimal one that causes the lockup? I can't seem to reproduce this with the snippet above, or other GLSL constructs.

**Comment by Toasterthegamer** [comment]
I can't seem to reproduce the error. I think at the time I had two conflicting visual studio extensions or something that was causing the issue.
