### ISSUE TITLE
shadow errors in Graphics level 10.

### ISSUE THREAD

**Issue by nug700** [SiliconStudio/paradox#222]
In graphics level 10 Having a directional light that casts a shadow causes errors during runtime.

[first Image](http://i.imgur.com/SxlwC8q.jpg)
[second Image](http://i.imgur.com/PmpsKOE.jpg)
[Error](https://gist.github.com/nug700/ce2a59f8aabbbc726119)

**Comment by jwollen** [comment]
This issue has been fixed on our development branch and will be integrated in the next release.
