### ISSUE TITLE
ParadoxShaderKeyGenerator in paradox 1.0 beta 10

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#224]
ParadoxShaderKeyGenerator generates wrong cs file for the *.pdxfx file.
1) start paradox studio 1.0.0 - beta 10;
2) Generate New project "Simple Model";
3) Open in  visual studio ide;
4) Regenerate SimpleModel3EffectMain.pdxfx file (delete SimpleModel3EffectMain.cs and resave SimpleModel3EffectMain.pdxfx);
5) ParadoxShaderKeyGenerator generates wrong cs file!!!

**Comment by xoofx** [comment]
Have you installed both side by side 1.1.x and the 1.0 beta? I think that our current code gen for shaders doesn't handle this well.

**Comment by Zulusas** [comment]
Yes i have installed both versions.

**Comment by jwollen** [comment]
The next version of the Visual Studio plugin will automatically select the appropriate Paradox SDK.
However we have deprecated 1.0. support in the plugin. To use it, the older package would have to be installed manually.
