### ISSUE TITLE
Compile error when adding 3rd party library

### ISSUE THREAD

**Issue by larhil** [SiliconStudio/paradox#230]
When adding a third party library such as the Windows AD SDK to the references of a 1.1.2. beta Windows Store project you will get this compile error.

1>  Patch for assembly [PoolPanic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
1>  Failed to resolve assembly: 'Microsoft.Advertising.WinRT.UI, Version=8.1.30809.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
1>  Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Advertising.WinRT.UI, Version=8.1.30809.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>     at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
1>     at SiliconStudio.AssemblyProcessor.ComplexSerializerCodeGenerator..ctor(IAssemblyResolver assemblyResolver, AssemblyDefinition assembly)
1>     at SiliconStudio.AssemblyProcessor.ComplexSerializerGenerator.GenerateSerializationAssembly(PlatformType platformType, BaseAssemblyResolver assemblyResolver, AssemblyDefinition assembly, String serializationAssemblyLocation, String signKeyFile, List`1 serializatonProjectReferencePaths)
1>     at SiliconStudio.AssemblyProcessor.SerializationProcessor.Process(AssemblyProcessorContext context)
1>     at SiliconStudio.AssemblyProcessor.AssemblyProcessorApp.Run(AssemblyDefinition& assemblyDefinition, Boolean& readWriteSymbols, Boolean& modified)
1>  Failed to resolve assembly: 'Microsoft.Advertising.WinRT.UI, Version=8.1.30809.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by Toasterthegamer** [comment]
This doesn't appear to be a paradox issue check here: 

http://forum.unity3d.com/threads/wp8-adcontrol-mono-cecil-assemblyresolutionexception.196766/

**Comment by larhil** [comment]
I'll give it a try. However it worked perfectly with Paradox 1.0 beta. After switching to Paradox SDK 1.1 and 1.2 beta it didn't work anymore. That's why I assume it has something to do with paradox.

Thanks...

**Comment by xenux** [comment]
It is confirmed that it has nothing to do with Paradox? Can I close the issue?

**Comment by xen2** [comment]
We might need to review AssemblyProcessor behavior for those assemblies that are not found and not actually needed at runtime.

**Comment by larhil** [comment]
It's very simple to reproduce.

1. Create "HelloWorld" with "Windows Store" project with Paradox 1.1.2-beta
2. Add the reference "Windows 8.1/Extension/Microsoft Advertising SDK for Windows 8.1 (Xaml)" come with VS Update 2.
3. Compile and get the error.

It works when you create a sample project with Paradox 1.1.0-beta.

**Comment by larhil** [comment]
The solution suggested by Toasterthegamer does not work because it occurs in a Windows Store project not in a Windows Phone project. Something changed in between 1.0.0-beta and 1.1.2-beta which caused this error.

**Comment by larhil** [comment]
Problem persists Paradox.1.1.3-beta.

**Comment by xen2** [comment]
Will be fixed in next release.
