### ISSUE TITLE
SetScissorRectangles issue (v1.1.3b)

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#231]
I got small issue with GraphicsDevice.SetScissorRectangles method.

This was working in 1.1.2b and it's not working anymore (sprite batch does not draw for some reason):

`manager.GraphicsDevice.SetScissorRectangles(clipRect);`

I replaced it with 

`manager.GraphicsDevice.SetScissorRectangles(clipRect.Left, clipRect.Top, clipRect.Right, clipRect.Bottom);`

which is working fine.

**Comment by xen2** [comment]
Thanks for the report.
BTW, current SetScissorRectangles is using params and does allocate arrays (we would need to reimplement it properly), so probably better to use SetScissorRectangles(int,int,int,int) for now.

**Comment by ikroeber** [comment]
Are you using DirectX or OpenGL?

**Comment by jwollen** [comment]
This is related to the above SharpDX issue and will be integrated soon.
