### ISSUE TITLE
FrustumCulling(v1.1.3b)

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#232]
Frustum culling did not working :(

**Comment by xenux** [comment]
HI Zulusas, 
can you tell us more about this? 
What is not working exactly?

**Comment by Zulusas** [comment]
I have created sample project based on materials sample:
https://dl.dropboxusercontent.com/u/46052374/Material113.zip

Usually, when frustum culling is enabled fps is higher when camera is directed to empty space, and fps is lower when camera directed to the group of entities (16x16x16 entities). In my sample fps is constant - 7FPS, there is no difference where camera is focused (to entities or to empty space).

**Comment by jwollen** [comment]
Thanks for reporting. There was indeed a bug, preventing it from working properly. The fix will be included in our next release.

**Comment by xen2** [comment]
Fixed in 1.1.4.
