### ISSUE TITLE
xaudio2_8.dll missing on win 7

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#233]
[AudioEngine]: Warning: One or more of the XAudio and MediaFoundation dlls were
not found on the computer. Audio functionalities will not fully work for the 
current game instance. To fix the problem install or repair the installation of 
XAudio and Media Foundation. [Exception details: Unable to load DLL 'xaudio2_8.dll':
 The specified module could not be found. (Exception from HRESULT: 0x8007007E)]

**Comment by xoofx** [comment]
Hi @Zulusas 
On which platform/OS are you trying this?

**Comment by Zulusas** [comment]
Win 7 64b

-----Pradinis laiškas-----
Nuo: "Alexandre Mutel" <notifications@github.com>
Išsiųsta: ‎2015-‎06-‎25 16:13
Kam: "SiliconStudio/paradox" <paradox@noreply.github.com>
Kopija: "Zulusas" <raimondas1978@gmail.com>
Tema: Re: [paradox] xaudio2_8.dll missing on win 7 (#233)

Hi @Zulusas 
On which platform/OS are you trying this?

**Comment by Benlitz** [comment]
Hello @Zulusas 

Does sound work, even if you get this warning?

**Comment by Zulusas** [comment]
No sound on "SimpleAudio" sample :(
