### ISSUE TITLE
Incorrect BlendState set to transparent materials created using MaterialDescriptor

### ISSUE THREAD

**Issue by HugoPeters** [SiliconStudio/paradox#235]
When using a _MaterialDescriptor_ with either the _MaterialTransparencyAdditiveFeature_ or the _MaterialTransparencyCutoffFeature_, the _BlendState_ in the final _Material_'s parameters isn't set to _BlendStates.AlphaBlend_. If you don't do this, the final material will lack any transparency. To fix this, right now you have to set it manually:

```csharp
Material.Parameters.Set(Effect.BlendStateKey, GraphicsDevice.BlendStates.AlphaBlend);
```

Also, for textures that already have a transparency byte, I have to add the transparency feature in what seems to me kind of a weird way:

```csharp
MD.Attributes.Transparency = new MaterialTransparencyAdditiveFeature() { Alpha = new ComputeFloat(1), Tint = new ComputeColor(Color4.White) };
``` 

That works, but it could be nicer in my opinion.

**Comment by xoofx** [comment]
Hi @HugoPeters 
The `Additive`  transparency is already using a custom blendstate as declared [here](https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Engine/Rendering/Materials/MaterialTransparencyAdditiveFeature.cs#L62) and should not be changed. 

The `Cutoff` transparency should not have a blendstate as it is only using a pixel discard instead.

As the `Additive` mode is a special mode combining both additive for specular (when MaterialTransparencyAdditiveFeature.Alpha < 0.5) and blending textures (MaterialTransparencyAdditiveFeature.Alpha > 0.5), we will add in the next release a simpler `Blend` transparency mode when only blending from the texture is required.

**Comment by HugoPeters** [comment]
@xoofx Ah, thanks a lot!
