### ISSUE TITLE
Paradox does not like enums

### ISSUE THREAD

**Issue by MathieuJack** [SiliconStudio/paradox#240]
Create the "CustomEffect" sample project with iOS.
Verify it's compiling/Running for iOS.
In the CustomEffect.Game project, create an enum, like:
	public enum Michel
	{
		A,
		B
	}

You get these errors:
1>  Serialization assembly compilation: 2 error(s)
1>EXEC(26,103): error CS0453: The type 'Michel' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'EnumSerializer<T>'
1>EXEC(51,195): error CS0453: The type 'Michel' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'EnumSerializer<T>'
1>  
1>  System.InvalidOperationException: Serialization assembly compilation: 2 error(s)
1>EXEC(26,103): error CS0453: The type 'Michel' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'EnumSerializer<T>'
1>EXEC(51,195): error CS0453: The type 'Michel' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'EnumSerializer<T>'
1>  
1>     à SiliconStudio.AssemblyProcessor.ComplexSerializerGenerator.GenerateSerializationAssembly(PlatformType platformType, BaseAssemblyResolver assemblyResolver, AssemblyDefinition assembly, String serializationAssemblyLocation, String signKeyFile, List`1 serializatonProjectReferencePaths)
1>     à SiliconStudio.AssemblyProcessor.SerializationProcessor.Process(AssemblyProcessorContext context)
1>     à SiliconStudio.AssemblyProcessor.AssemblyProcessorApp.Run(AssemblyDefinition& assemblyDefinition, Boolean& readWriteSymbols, Boolean& modified)
1>  Serialization assembly compilation: 2 error(s)
1>EXEC(26,103): error CS0453: The type 'Michel' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'EnumSerializer<T>'
1>EXEC(51,195): error CS0453: The type 'Michel' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'EnumSerializer<T>'

If ever you hit F5 again, then the app starts to run on iOS, but quickly you get an unhandled exception.

Remove the enum, everything works again.

**Comment by xen2** [comment]
Thanks for the feedback.

This is a known issue that is already fixed for our next major release (1.2).
I will try to backport it for 1.1.4 (that should be released today hopefully).

**Comment by xen2** [comment]
Fixed in 1.1.4
