### ISSUE TITLE
Why put Serialization and Deserialization in the same method?

### ISSUE THREAD

**Issue by boriscallens** [SiliconStudio/paradox#247]
Why does DataSerializer have a Serialize method that does both serialization and deserialization?
It seems like all implementations have a body that just contains two code paths split up by an if based on the ArchiveMode.

I must admit I have seen this pattern before in serialization code examples and libraries.
What is the disadvantage of having both a Serialize and Deserialize method and dump the archive mode parameter?

**Comment by xen2** [comment]
This patterns try to encourage user to write a code that works for both (so they are properly in sync).

Serialize(ref obj) can work both for serialization and deserialization.

As an example, f you have ``class A { int B; }``, you could write ``Serialize(ref a.B)`` without any if/else branching.
