### ISSUE TITLE
1.2 Beta Launcher fails to launch Paradox

### ISSUE THREAD

**Issue by jonstelly** [SiliconStudio/paradox#248]
Open the launcher, click the "Start 1.2.0-beta" button.  it turns dark for about .5 seconds, turns a bit more transparent for about 3-4 seconds, then pops right back to enabled, but never launches Paradox Studio.

**Comment by jonstelly** [comment]
An update to possibly help reproduce.

I had 1.1 launcher and studio installed.  Upgraded to 1.2 beta.  I had the environment variable set up to point to my github branch to use my local build at the time when I ran the upgrade (in case that matters).

I tried removing and re-adding 1.2 engine/libraries without removing Studio or the Launcher, but that didn't fix it.

I uninstalled Paradox, downloaded and installed the new build and everything's working fine now.

**Comment by xenux** [comment]
Thank you for the report and the workaround!
We will fix that as soon as possible

**Comment by HugoPeters** [comment]
I had the same thing happening. The fix is indeed to install v1.2 with the new launcher, as this will also install the prequisites, which doesn't seem to happen when using the old launcher.

**Comment by xenux** [comment]
We decided not to fix this issue as pre-requisites are correctly installed by the new launcher (1.2) and most of our users having updated from launcher 1.1 have already performed the install fix using the workaround.

**Comment by xen2** [comment]
Actually it has been fixed in newest launcher for people that still didn't upgrade!
