### ISSUE TITLE
1.2 Beta Crash

### ISSUE THREAD

**Issue by Krakean** [SiliconStudio/paradox#250]
1. Start 1.2.0 Beta
2. New Game, all defaults
3. "Select"
4. Direct3D 11.0, only Windows, OK.
5. Result: crash chain. First comes driver crash (http://gyazo.com/df1b62a1d5fd767152c0233777754b1a), then scene crash http://gyazo.com/d77ba6551cc33f8404d3e26aac152ce5 and finally studio crash - http://gyazo.com/6a2255bdd4a989759a6a13da94846503

So, question is: where is log files with useful info which can help you to understand why crashes  happens?
In case if it matters: my laptop - http://www.newegg.com/Product/Product.aspx?Item=N82E16834231631 - with Intel 4600 (drivers - 10.18.14.4222) and GeForce 870M (drivers - 10.18.13.5330). Paradox is running by default via Intel Gfx. There is no crash if I run it via dedicated graphics (i.e. 870M)

**Comment by jwollen** [comment]
Thanks for reporting!

This seems to be caused by an intel driver bug. We will work around it in the upcoming release.
