### ISSUE TITLE
Suggestion: Children / Parent accessors for Entity

### ISSUE THREAD

**Issue by HugoPeters** [SiliconStudio/paradox#251]
Since a few versions the "AddChild" method has been added to 'Entity'.
The description reads it only adds the child to the transform component of the root.
It might be cool/useful to have more concrete "child entities", that are treated as actual 'entities' instead of just the transform component.

Right now, to get the parent/children of an Entity, you'd have to do this:
Entity.Transform.Parent.Entity, or Entity.Transform.Children[idx].Entity.

Seems kind of inefficient to me, as it could just be:
Entity.Parent, or Entity.Children[idx]. (or even better, as generic methods, so that you could cast it to your own type at the same time, like the AddChild<T> method)

Do your magic, Paradox team, please make it happen! :)

**Comment by xenux** [comment]
Thanks for the report. 
We agree that the current API is not really great for that. We will make what is needed ;)
