### ISSUE TITLE
Newly created blank project cannot find Profiler

### ISSUE THREAD

**Issue by Krakean** [SiliconStudio/paradox#255]
When we create, for example, blank newgame project, we can see this line in MyGameApp.cs->Main():
// Profiler.EnableAll();
But, uncommenting it lead to error with inability to find Profiler. Which is can be solved easily by adding using SiliconStudio.Core.Diagnostics;
So, question is: why not add "using SiliconStudio.Core.Diagnostics;" when generating blank project? So when newcomer uncomment Profiler line, he will not get error. Otherwise, why not remove "Profiler.EnableAll()" if anyway uncommenting it lead to compile error?

**Comment by xenux** [comment]
Thanks for the report, 
We probably removed the "using SiliconStudio.Core.Diagnostics;" by accident at some point. We will fix that!
