### ISSUE TITLE
GraphicsDevice.Destroy does not dispose DepthStencilStates

### ISSUE THREAD

**Issue by amerkoleci** [SiliconStudio/paradox#257]
It disposes SamplerStates, RasterizerStates and BlendStates, missing DepthStencilStates.Dispose(); invocation.

**Comment by xenux** [comment]
Thanks for the report. It will be fixed for next release.

**Comment by xen2** [comment]
Fixed by https://github.com/SiliconStudio/paradox/commit/1a2b97b964f37589cd30b38697aa4d3b9eb9a105
