### ISSUE TITLE
[Visual Studio Extensions] Default syntax highlight colors 

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/paradox#26]
Hi,

Could you please improve the default syntax highlight colors for the various VS themes.  The shaders and YAML files currently are a bit hard on the eyes when using the dark theme.

Cheers,
dfkeenan

**Comment by discosultan** [comment]
What's weird is that whenever I press _Use Defaults_ in the _Fonts and Colors_ dialog, the syntax highlight colors for _.xksl_ files will be reverted back to this: ![syntax highlight colors](https://cloud.githubusercontent.com/assets/750121/4751398/8af309ea-5a9d-11e4-92ba-2f83e52f1ea8.png)
