### ISSUE TITLE
Error occur by the language item of the international settings in Visual Studio

### ISSUE THREAD

**Issue by EternalTamago** [SiliconStudio/paradox#264]
If it is "Japanese", when the Visual Studio opens a project file of Paradox, the following error message is output.

```
Error loading Paradox SDK: System.ArgumentException: パラメーターが間違っています。 (HRESULT からの例外:0x80070057 (E_INVALIDARG))
   場所 EnvDTE.OutputWindowPanes.Item(Object index)
   場所 SiliconStudio.Paradox.VisualStudio.Commands.BuildMonitorCallback..ctor(DTE2 dte)
   場所 SiliconStudio.Paradox.VisualStudio.ParadoxPackage.InitializeCommandProxy()
```

Perhaps, in a non-English environment, there may be a possibility that does not exist "Build" pane by localization.

Paradox 1.2.1/Launcher 1.2.1/Installation Options [only for me].
Visual Studio 2015 Community
Windows 10 Pro x64

**Comment by h-sao** [comment]
レポートありがとうございます、すぐに確認します！
Thank you for your comments. We'll check it and get back to you as soon as possible.

**Comment by xen2** [comment]
Could you please "Reinstall" Visual Studio Package from Paradox Launcher?
New version should fix that issue.

**Comment by EternalTamago** [comment]
After I launched the launcher for re-installation, the launcher has been updated automatically to v1.3.0.
I was able to update the Visual Studio plugin from the update button.
Then the error has not occurred.

Thank you very much!

**Comment by xen2** [comment]
Thanks for checking it again, closing then!
