### ISSUE TITLE
Which files should be managed by Git version control?

### ISSUE THREAD

**Issue by yanglee** [SiliconStudio/paradox#267]
Hello,

New to game development. I noticed other than Visual Studio solution and project files, Paradox also created the following files and folders:

/Assets
/RawAssets
*.pdxpkg
*.props

Should all of them be managed by Git version control?

**Comment by xen2** [comment]
They should all be in version control, except the *.user files (i.e. MyGame.pdxpkg.user -- we chose .user because most user already have this already in their default .gitignore for Visual Studio).

Of course you should also have default Visual Studio ignore:
obj
bin
*.suo
etc...

**Comment by xen2** [comment]
Note: we discussed about this internally and were thinking it might be a good idea to maybe auto-generate this file when creating a new project, what do you think?

**Comment by yanglee** [comment]
Thanks for your answer :)

Do you mean auto generate the .gitignore file? That would be nice :)

**Comment by Therzok** [comment]
@xen2 What about people using HG or svn? I think a sample file would be better and in the project a file (maybe a README) could refer to it?

Another solution would be to put one here (https://github.com/github/gitignore), and people could grab it using VS' GitHub Experience.

**Comment by xen2** [comment]
@Therzok Wasn't aware of the second option, thanks for pointing this out!
