### ISSUE TITLE
Some Prerequisites could not be downloaded. (MSBuild 2015 RC)

### ISSUE THREAD

**Issue by najak3d** [SiliconStudio/paradox#271]
For me, when I attempt installation on Windows 7 Home Premium, I get this error while trying to install the prerequisites (I think for Visual Studio):

"Some prerequisites could not be downloaded...."

And the only one it's trying to download is "MSBuild 2015 RC".

When I googled for this, I didn't find any clear-cut package to download.  Is there a web link that will give me what I need?   It would be better of course, if the Paradox installer just found it and got it for me, of course.

**Comment by xen2** [comment]
Thanks for the feedback

You can find an answer here:
http://forums.paradox3d.net/t/cant-download-ms-build-tools-rc/337

New release that will fix this properly should be available within a few hours, we are currently testing it!

**Comment by xen2** [comment]
New release should fix this. Please reopen if you still have issue with 1.2.2.
