### ISSUE TITLE
Weird Camera frustum in editor

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#278]
Looks like editor has problems with negative rotations on camera. Camera view is correct, but wire camera frustum in editor is wrong.

![editorcameraerror](https://cloud.githubusercontent.com/assets/7707327/9330531/496214fe-45ba-11e5-8c1d-8ad14011a74b.png)

**Comment by Benlitz** [comment]
Thanks for reporting, there was indeed an error in the code that computes the camera gizmo matrix.

This has been fixed internally and will be a part of the next release.
