### ISSUE TITLE
Custom Asset error

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#280]
Hi, I followed docs about creating custom asset type and I'm getting exception in editor (below). I can see RangeAsset in menu. I added object factory attribute like you have for your assets, but still not working. Serializer is missing for RangeAsset. How can I create one?

Paradox Version: 1.2.2-beta
GameStudio Version: 4

InnerException:
  ArgumentException: No serializer available for type TestLib.RangeAsset
     at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer)
     at SiliconStudio.Core.Serialization.SerializerExtensions.SerializeExtended[T](SerializationStream stream, T obj, ArchiveMode mode, DataSerializer`1 dataSerializer)
     at SiliconStudio.Assets.AssetCloner..ctor(Object value, Boolean keepOnlySealedOverride, Boolean referencesAsNull)
     at SiliconStudio.Assets.AssetCloner.Clone(Object asset, Boolean keepOnlySealedOverride, Boolean referencesAsNull)
     at SiliconStudio.Assets.Analysis.AssetDependencyManager.TrackAsset(Guid assetId)
     at SiliconStudio.Assets.Analysis.AssetDependencyManager.TrackAsset(AssetItem assetItemSource)
     at SiliconStudio.Assets.Analysis.AssetDependencyManager.Assets_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
     at SiliconStudio.Assets.PackageAssetCollection.Add(AssetItem item)
     at SiliconStudio.Assets.Editor.ViewModel.AssetViewModel.UpdateProject()
     at SiliconStudio.Presentation.ViewModel.ViewModelBase.SetValue[T](T& field, T value, Action updateAction, String[] propertyNames)
     at SiliconStudio.Presentation.ViewModel.EditableViewModel.SetValue[T](T& field, T value, Action updateAction, String[] propertyNames)
     at SiliconStudio.Presentation.ViewModel.ViewModelBase.SetValue[T](T& field, T value, Action updateAction, String propertyName)
     at SiliconStudio.Assets.Editor.ViewModel.AssetViewModel.set_IsDeleted(Boolean value)
     at SiliconStudio.Assets.Editor.ViewModel.AssetViewModel..ctor(AssetViewModelConstructionParameters parameters)

**Comment by Benlitz** [comment]
Hi,

Did you add a DataContract attribute? Does your asset class has a parameter-less constructor? (I think it should be either public or internal)

**Comment by EmptyKeys** [comment]
Yeah, have both.

`
[DataContract("RangeAsset")] // Name of the Asset serialized in YAML    
    [AssetCompiler(typeof(RangeAssetCompiler))] // The compiler used to transform this asset to RangeValues
    [AssetDescription(".pdxrange")] // A description used to display in the asset editor
    [ObjectFactory(typeof(RangeAssetFactory))]    
    public class RangeAsset : Asset
    {
        public float From { get; set; }
        public float To { get; set; }
        public float Step { get; set; }

        public RangeAsset()
            : base()
        {
        }

        private class RangeAssetFactory : IObjectFactory
        {            
            public object New(Type type)
            {
                return new RangeAsset();
            }
        }
    }
`

**Comment by Benlitz** [comment]
You probably need to register a module initializer as well for the assembly containing the asset, try to add a class similar to this one:

    internal class Module
    {
        [ModuleInitializer]
        public static void Initialize()
        {
            AssemblyRegistry.Register(typeof(Module).Assembly, AssemblyCommonCategories.Assets);
        }
    }

**Comment by EmptyKeys** [comment]
It didn't help much, still the same exception. I followed this

http://doc.paradox3d.net/1.2/?page=Creating+a+custom+asset+-+step+by+step

tho I had to fix few things. Maybe it would be easier to create simple example for this. I really need custom assets, my game is full of them.

**Comment by sinkingsugar** [comment]
What kind of Visual Studio project is the one that is compiling this asset assembly ? It could be that it's not being processed by the AssemblyProcessor.

**Comment by EmptyKeys** [comment]
It's standard class library and I added few references. Do I have to create something special for AssemblyProcessor?

**Comment by sinkingsugar** [comment]
Ok, You have to edit the csproj file.
So, taking a look at https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Assets/SiliconStudio.Paradox.Assets.csproj for example
You need the two lines from top with tags: SiliconStudioAssemblyProcessor and SiliconStudioAssemblyProcessorOptions
You also need one line from the bottom: <Import Project="$(SiliconStudioPostSettingsTargets)" />

**Comment by EmptyKeys** [comment]
OK, I changed project file a bit and It's working. :)

I can create custom asset in editor now. Thanks guys for help.

**Comment by EmptyKeys** [comment]
Hmm I can create custom asset, I can see it in asset view, but Build Engine does not compile it for the game. Looks like RangeAssetCompiler is not called at all.

**Comment by sinkingsugar** [comment]
Would be helpful to see the Compiler class and such, but anyway I'm assuming you used an existing one as inspiration ( Need to override right things and create build step etc ).
Also how are you using this asset GameStudio wise? are you able to add it where you need it etc?

**Comment by EmptyKeys** [comment]
Compiler below. I think something still not working correctly. I can add asset in menu, I can see it in asset view, I can set value, I can see asset on HDD with proper values, but if I close Game Studio and open it again asset is gone. It's still on HDD.

```
internal class RangeAssetCompiler : AssetCompilerBase<RangeAsset>
    {
        protected override void Compile(AssetCompilerContext context, string urlInStorage, UFile assetAbsolutePath, RangeAsset asset, AssetCompilerResult result)
        {
            result.BuildSteps = new ListBuildStep() { new RangeAssetCommand(urlInStorage, asset) };
        }
        /// <summary>
        /// Command used by the build engine to convert the asset
        /// </summary>
        private class RangeAssetCommand : AssetCommand<RangeAsset>
        {
            public RangeAssetCommand(string url, RangeAsset asset)
                : base(url, asset)
            {
            }

            protected override Task<ResultStatus> DoCommandOverride(ICommandContext commandContext)
            {
                var assetManager = new AssetManager();
                // Generate our data for in-game time
                var inGameAsset = new RangeValues();
                
                for (float index = 0; index <= 40; index += 1)
                    inGameAsset.Values.Add(index);
                // Save in-game asset
                assetManager.Save(Url, inGameAsset);
                return Task.FromResult(ResultStatus.Successful);
            }
        }
    }
```

**Comment by sinkingsugar** [comment]
I think that your runtime type is missing some attributes (in this case RangeValues).
Take a look at:
https://github.com/SiliconStudio/paradox/blob/master/sources/engine/SiliconStudio.Paradox.Physics/Engine/PhysicsColliderShape.cs

specially:

[DataSerializerGlobal(typeof(CloneSerializer<PhysicsColliderShape>), Profile = "Clone")]
[DataSerializerGlobal(typeof(ReferenceSerializer<PhysicsColliderShape>), Profile = "Asset")]

**Comment by EmptyKeys** [comment]
I added attributes, but it didn't help.

**Comment by sinkingsugar** [comment]
Yesterday I actually replicated the whole issue. 
While we have within the game studio the possibility to add a new PCL library we are lacking the infrastructure to add an actual windows native library (not just that, few small things to make it compile assets as well) in order to customize assets and build them.
Should not be too long, we added it the task in the pipeline.
In the meantime you could just add your custom asset within the engine (SiliconStudio.Paradox.Assets) and compile with the engine itself.

**Comment by sinkingsugar** [comment]
There is also another little step if you follow the "whole engine" compilation approach (which we should also fix in order to allow external assets properly).
You will need to add your asset to a dictionary in ParadoxDefaultAssetsPlugin.cs file, like:
contentTypes.Add(typeof(ColliderShapeAsset), typeof(PhysicsColliderShape));
This is necessary to associate an editor asset type to a run-time engine type. And allows you drag-n-drop and so on.

**Comment by jwollen** [comment]
I don't believe this is necessary. I'm using custom assets in external projects, too, and they appear to work fine.

Besides Asset, AssetCompiler, ModuleInitializer and the AssemblyProcessor running, nothing should be needed. Could you upload a working project (e.g. to [Gist](https://gist.github.com/)), so I can have a look?

**Comment by EmptyKeys** [comment]
Simple test game here
https://github.com/EmptyKeys/Sandbox/tree/master/Paradox3dTests

**Comment by jwollen** [comment]
This was indeed a bug, when assets are used in the same package they are defined in.
We fixed it internally and it should soon be available!
