### ISSUE TITLE
[Launcher]crashed by a limited font at WpfAdapter in HTML-Renderer

### ISSUE THREAD

**Issue by WyPeR** [SiliconStudio/paradox#291]
My pull request ( https://github.com/ArthurHub/HTML-Renderer/commit/e05e700f7ef6dae60adfba0f48d8a7fc53760234 ) is merged.

A replace should do these modules.

**Comment by Benlitz** [comment]
Thank you for the fix, we will propagate it on our own fork of HTML-Renderer.
