### ISSUE TITLE
SyncScript.Start() not called on Clones

### ISSUE THREAD

**Issue by wanderwurst** [SiliconStudio/paradox#294]
Using Clone() on an Entity that has SyncScripts attached does clone those scripts. However the Start() method never gets called on the cloned scripts.

To me it would make sense, if Start() was called either right during Clone(), or (maybe even preferably) when adding the clone to the scene, i.e.
SceneSystem.SceneInstance.Scene.AddChild(clone);

No biggy, since I can manually run Start() after Cloning/Adding. Maybe that is even the intended way of doing things?

**Comment by jwollen** [comment]
Hi, thanks for the report!

I tried to reproduce this and Start() seems to be called correctly, when adding the Entity to the Scene. You should never need to call any of the methods on scripts.

Note that it will not be called immediately, but deferred until the beginning of the next frame. If that's not the case for you, could you post the code where you clone and add the Script?

**Comment by wanderwurst** [comment]
Wow, thanks for the impressively fast feedback! :-)
Right now I have quite some code in the Start() of another Script, which finds a reference Entitiy in the Scene and clones it multiple times. I will try to boil it down to something minimial but reproducable and get back here with my findings.
Thanks again.
Sven

**Comment by wanderwurst** [comment]
Ok, here is what I do:

Create a new project with Beta 1.2.2 (the official downloadable one) with VS 2015 Community on Windows 7 x64 (all the latest updates on everything). On the new project dialog I leave everything set to default, so I get the default scene with the ground, the skybox and the sphere.

In VS I create two scripts.
Script one to multiply the reference instance:
```C#
using SiliconStudio.Paradox.Engine;

namespace SyncStartTest
{
    public class Multiply : SyncScript
    {
        public Entity ReferenceEntity = null;
        public float CloneCount = 10;

        public override void Start()
        {
            base.Start();

            if (ReferenceEntity != null)
            {
                for (int i = 0; i < CloneCount; i++)
                    SceneSystem.SceneInstance.Scene.AddChild(ReferenceEntity.Clone());
            }
        }

        public override void Update()
        {
        }
    }
}
```

And script two to modify the initial position:

```C#
using SiliconStudio.Paradox.Engine;

namespace SyncStartTest
{
    public class IncreaseOffset : SyncScript
    {
        static float X = 0;

        public override void Start()
        {
            base.Start();

            this.Entity.Transform.Position.X = X;

            X += 1;
        }

        public override void Update()
        {
        }
    }
}
```

In Studio, I attach the `IncreaseOffset` script to the default Sphere.
I also create an empty Entity to attach the `Multiply` script to and set the ReferenceEntity to be the sphere.

Now I run the project. 
With breakpoints, I can step through the code showing me the following order of events:
-IncreaseOffset.Start() is called on the reference sphere
-Multiply.Start() is called for the empty entitiy holding it
-In the loop inside Start(), 10 clones of the sphere are created and added to the scene
-The IncreaseOffset script is also cloned and thus a part of all of them, but the Start() method never gets called on any of the clones (the breakpoint there is never hit again and they all end up at in the same location)

It might of course just turn out that I am not using the things the way they are supposed to be used? 

Regards,
 Sven

**Comment by jwollen** [comment]
Thanks for the details!
This was indeed a bug. The fix will be on Github soon, and part of the next release.

In the meantime you could turn that SyncScript into an AsyncScript and do the cloning at the beginning of Execute().
