### ISSUE TITLE
Strange dependencies on independent lights

### ISSUE THREAD

**Issue by wanderwurst** [SiliconStudio/paradox#297]
After trying more things, I found a much easier way to produce the problem. It seems like an interference of lights to me which I would not expect:

In a fresh new project, create a Spot Light. Set Range to 4 and Intensity to 30. You should see the light on the default sphere and the ground around it.
Add a second spot light, set range also to 4 and Intensity to 30. Move it a bit away, e.g. I set X to 2.
The light has the wireframe thing, but no light is rendered.
Select the first light. Disable it by clicking the "Light" checkbox in component header of the property grid. Now light 2 comes on. I can toggle light 2 by switching light 1 on and off.

Am I am doing something completely wrong here? I wouldnt expect these lights to interfere, they are independent entities after all?

-----------------------------
old post (for reference)

In a fresh new project (Official beta 1.2.2, Win7, VS2015) I create the following hierarchy of objects:
```
|__EmptyEntity1
   |__PointLight1
   |__EmptyEntity2
      |__PointLight2
```
In VisualStudio I create a simple script to toggle a light on and off and attach it to PointLight1
```
using SiliconStudio.Paradox.Engine;

namespace ToggleTest
{
    public class LightOnOff : SyncScript
    {
        private LightComponent _light;

        public override void Start()
        {
            _light = this.Entity.Get<LightComponent>();
        }

        private int frameCount = 0;

        public override void Update()
        {
            if (frameCount++ == 60)
            {
                frameCount = 0;
                _light.Enabled = !_light.Enabled;
            }
        }
    }
}
```
Running the project, PointLight1 is toggled on and off each second as expected.

Now I rightclick PointLight2 in the MainScene hierarchical list in Paradox Studio and choose "Duplicate selected items" to create this hierarchy:
```
|__EmptyEntity1
   |__PointLight1
   |__EmptyEntity2
      |__PointLight2
      |__PointLight2Clone
```
Running the project again, PointLight1 AND PointLigh2Clone are now toggled on and off. To my understanding, PointLight2Clone should not be affected by a script attached to PointLight1?

In the debugger, I can see that my script is only called once each second with the _light reference always refering to PointLight1. So it does not look like the script gets attached to the clone, it's rather some internal issue that doesn't seem like intended behaviour to me. Or am I just doing something wrong with how I store my _light reference at script start?

Deleting the clones and instead just creating new objects from scratch works fine for me.

**Comment by wanderwurst** [comment]
Actually after fiddling some more, it turns out the issue also happens if I just manually add more PointLights to EmptyEntity2, without ever using the Duplicate function. However it behaves much more randomly whereas the above seems to reliably reproduce the issue.

**Comment by jwollen** [comment]
Thanks for the report!

Your usage is perfectly fine. This was due to a bug in the rendering code, where not all enabled lights would be drawn. It's now fixed internally and will be part of the upcoming release.

**Comment by wanderwurst** [comment]
Great news, thanks a lot!
Looking forward to the release to get my landing strip all nice and shiney ;-)
