### ISSUE TITLE
Cannot build solution with code library

### ISSUE THREAD

**Issue by Mylan719** [SiliconStudio/paradox#300]
I have trouble getting build to work basicly as soon as I use anything that has to do with referencing libraries in Visual studio.
I have discused the issue in this topic:
http://forums.paradox3d.net/t/cannot-build-solution-with-code-library/373

**Comment by xenux** [comment]
@Mylan719 the topic on the forum seems to be solved so I close the issue. If there is still some problems don't hesitate to reopen.
