### ISSUE TITLE
FontManager SharpFont dispose crashes on Windows x64 mode

### ISSUE THREAD

**Issue by amerkoleci** [SiliconStudio/paradox#305]
SharpFont Library dispose method being called from FontManager Dispose method fails with null reference exception when running on Windows/x64 mode.
Probably internal issue in your SharpFont library build.

**Comment by xenux** [comment]
Thanks for the report.
Could you be a little more precise about the reproduction?
I ran the Sprite Fonts sample on windows desktop x64 but I did not experienced any crash during the disposal of SharpFont.

**Comment by xenux** [comment]
Closing the issue as we could not reproduce it.
