### ISSUE TITLE
1.3.1b New Game template builds and runs in editor but fails after opening Visual Studio 2015

### ISSUE THREAD

**Issue by ricardo2097** [SiliconStudio/paradox#307]
After opening IDE (Visual Studio 2015 community) I start getting this message on build:
[TestGameApp.cs(9,35)]: Error: 'Game' is a namespace but is used like a type

using SiliconStudio.Paradox.Engine;

namespace TestGame
{
    class TestGameApp
    {
        static void Main(string[] args)
        {
            using (var game = new Game())
            {
                game.Run();
            }
        }
    }
}

**Comment by Benlitz** [comment]
Hello,

Could you check that you have the SiliconStudioParadoxDir environment variable that is correctly set to the path where you installed Paradox?

In the meantime, you can probably compile your project if you start Visual Studio from the Game Studio  (there is an icon in the top toolbar to open Visual Studio).
The Game Studio overwrites this variable when it opens VS.

**Comment by ricardo2097** [comment]
Indeed I used the button on the Paradox Editor to open IDE (VS2015).
Before opening VS2015 for the first time the New Game Template was building. After opening VS2015 and no manual changes it stops building with this issue of namespace vs type.
I have no issues now after pointing manually to the app type (the original type from SiliconStudio.Paradox.Engine namespace or my extended class)
VS2015 seems to be giving priority to the Project namespace structure and not the using SiliconStudio.Paradox.Engine
