### ISSUE TITLE
Can't compile new empty project because path to ParadoxReferences.cache does not exist

### ISSUE THREAD

**Issue by boriscallens** [SiliconStudio/paradox#310]
Tried to create a new project through the launcher. The "creating session..." window hangs (close does nothing, have to use task manager) with the following output:

	[]: Info: Loading Assets from Package [Paradox.pdxpkg]
	[]: Info: Loading Assets from Package [MyGame3.pdxpkg]
	[]: Info: Generate MyGame3.Game
	[]: Info: Generate MyGame3.Windows
	[]: Info: Loading Assets from Package [MyGame3.pdxpkg]
	[C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Targets\Paradox.targets(141,5)]: Error: The command ""C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization  --add-reference="C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Paradox.Physics.dll" --add-reference="C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Paradox.SpriteStudio.Runtime.dll" --references-file="obj\Windows\Debug\ParadoxReferences.cache" "obj\Windows\Debug\MyGame3.Game.dll"" exited with code 1.
	[]: Error: Unable to build assembly reference [F:\Tests\MyGame3\MyGame3\Bin\Windows\Debug\MyGame3.Game.dll]

Running the same executable from command line gives more info:

	Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\obj\Windows\Debug\ParadoxReferences.cache'.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
	   at System.IO.StreamReader..ctor(String path, Encoding encoding)
	   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
	   at System.IO.File.ReadAllLines(String path)
	   at SiliconStudio.AssemblyProcessor.AssemblyProcessorProgram.<>c__DisplayClass3_0.<CreateAssemblyProcessorApp>b__12(String v)
	   at Mono.Options.OptionSet.<>c__DisplayClass3.<Add>b__2(OptionValueCollection v)
	   at Mono.Options.OptionSet.ActionOption.OnParseComplete(OptionContext c)
	   at Mono.Options.Option.Invoke(OptionContext c)
	   at Mono.Options.OptionSet.ParseValue(String option, OptionContext c)
	   at Mono.Options.OptionSet.Parse(String argument, OptionContext c)
	   at Mono.Options.OptionSet.Parse(IEnumerable`1 arguments)
	   at SiliconStudio.AssemblyProcessor.AssemblyProcessorProgram.CreateAssemblyProcessorApp(String[] args, OptionSet& p, Boolean& showHelp, String& outputFilePath, List`1& inputFiles)
	   at SiliconStudio.AssemblyProcessor.AssemblyProcessorProgram.Main(String[] args)

The command seems to expect the path
> C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\obj\Windows\Debug\ParadoxReferences.cache

but there is no obj folder in the Windows-Direct3D11 folder.
Force quite all the paradox related processes and relaunched it, same effect.
Tried compiling from Visual studio, no difference.
Tried SiliconStudio.ExecServer.exe

Paradox: 1.3.2 beta
Windows: 10 pro
Visual studio: 2015

**Comment by xoofx** [comment]
Weird, I can't reproduce this. The obj folder is normally the one from your project and MSBuild is usually running the command from your project...
Could you put VS log in diagnostics mode (`Tools\Options\Project And Solutions\Build And Run\MSBuild project build output verbosity`) and attach it here?

**Comment by boriscallens** [comment]
Rebuild output with verbosity to diagnostics: https://gist.github.com/boriscallens/1a5d6d30a6c2495e9bee#file-build-log

**Comment by boriscallens** [comment]
Tried uninstalling and then re-installing paradox entirely, but still the same.
I repaved my entire machine last weekend for the windows 10 upgrade so there should be minimal interfering programs.

**Comment by xoofx** [comment]
Actually, the error is happening on the `MyGame2.exe`. It is like the process was already running...

```
2>  "C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization --add-reference="F:\Tests\MyGame2\MyGame2\Bin\Windows\Debug\MyGame2.Game.dll" --add-reference="C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Paradox.Physics.dll" --add-reference="C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Paradox.SpriteStudio.Runtime.dll" --references-file="obj\Windows\Debug\ParadoxReferences.cache" "obj\Windows\Debug\MyGame2.exe" (TaskId:94)
2>  The process cannot access the file 'F:\Tests\MyGame2\MyGame2\MyGame2.Windows\obj\Windows\Debug\MyGame2.exe' because it is being used by another process. (TaskId:94)
2>  System.IO.IOException: The process cannot access the file 'F:\Tests\MyGame2\MyGame2\MyGame2.Windows\obj\Windows\Debug\MyGame2.exe' because it is being used by another process. (TaskId:94)
2>     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) (TaskId:94)
2>     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) (TaskId:94)
2>     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) (TaskId:94)
2>     at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share) (TaskId:94)
2>     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) (TaskId:94)
2>     at SiliconStudio.AssemblyProcessor.AssemblyProcessorApp.Run(AssemblyDefinition& assemblyDefinition, Boolean& readWriteSymbols, Boolean& modified, ILogger logger) (TaskId:94)
2>  The process cannot access the file 'F:\Tests\MyGame2\MyGame2\MyGame2.Windows\obj\Windows\Debug\MyGame2.exe' because it is being used by another process. (TaskId:94)
2>   (TaskId:94)
2>   (TaskId:94)
2>C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Targets\Paradox.targets(141,5): error MSB3073: The command ""C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization --add-reference="F:\Tests\MyGame2\MyGame2\Bin\Windows\Debug\MyGame2.Game.dll" --add-reference="C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Paradox.Physics.dll" --add-reference="C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Paradox.SpriteStudio.Runtime.dll" --references-file="obj\Windows\Debug\ParadoxReferences.cache" "obj\Windows\Debug\MyGame2.exe"" exited with code 1.
2>  Output Property: SiliconStudioAssemblyProcessorErrorCode=1 (TaskId:94)
```

**Comment by boriscallens** [comment]
I investigated further with the same process

  - Clean new project
  - Kill paradox studio process (they are hanging)
  - Reboot (no uncertainty, takes only few seconds)
  - Disable AV (just in case)
  - Open VS2015 Pro
  - Open new project
  - Rebuild
  - Check verbose output
  - GOTO: rebuild

I encounter one of two kinds of errors on each build

> Unexpected exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.InvalidOperationException: Could not load native library assimp-vc120-mt.dll from path [C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.3.2-beta\Bin\Windows-Direct3D11\.shadow\SiliconStudio.Assets.CompilerApp_ExecServer.exe\assembly\dl3\native\cb58d8ef\assimp-vc120-mt.dll] using CPU architecture x64. (TaskId:119)

And 

>  System.IO.IOException: The process cannot access the file 'F:\Tests\MyGame5\MyGame5\MyGame5.Game\obj\Windows\Debug\MyGame5.Game.dll' because it is being used by another process. (TaskId:25)

I can't seem to find why one or the other is fired.
Also wondering if one is the cause of the other.

Reading up on procmon to see if I can capture what exactly is causing the file lock in the second case. As for the first case: the file doesn't exist anywhere in the ...native/** folder. Unsure what's happening there.

Could it have to do anything at all with directx12?

**Comment by xoofx** [comment]
Can you install the x64 of [VS 2013 C++ Redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=40784)? (They should be already installed, so I'm not sure it will fix anything...)

**Comment by boriscallens** [comment]
Noticed there is a version 1.3.3 available. Updating to that first (is taking a while).
If things still fail I'll try that.

**Comment by boriscallens** [comment]
Well updating didn't change anytyhing. I'm going to install the vs redistributables. But according to [the release notes](https://github.com/SiliconStudio/paradox/blob/d0f2e856c35f21a2dcad6585e9f921b87a6198af/doc/ReleaseNotes/ReleaseNotes.1.3.md#breaking-changes) it should be the [Visual C++ Redistributable for Visual Studio 2015 ](http://www.microsoft.com/en-eg/download/details.aspx?id=48145) right?
As it was already are already installed, I tried repairing it, but nothing changed.

I did notice however the very first time I try to build a Paradox project from Visual Studio I get a slightly different message in the output:

> CSC : error CS0006: Metadata file 'F:\Tests\MyGame\MyGame\Bin\Windows\Debug\MyGame.Game.dll' could not be found
The file is indeed not there, only the manifest and the vshost files are there.

When (re)building the same project a second time around this message doesn't seem to occur.
Any more ideas or things I can check out?

**Comment by xoofx** [comment]
Assimp is still compiled with VS2013 so the first errors you noticed could be related to this. I can't comment on other errors, as they are more likely a side effect of an original problem.

**Comment by boriscallens** [comment]
Well, tried with the vc++ vs2013 redistributables, reinstalled visual studio, reinstalled paradox.
Non paradox projects run fine, all paradox projects (new or old) are uncompilable.

I'm stumped.

**Comment by sinkingsugar** [comment]
Assimp indeed needed vs2013 redist and so do some other dependencies still actually. So that was one issue.

CS0006 is because you are trying to build the game Windows project without having built the pcl game project. This is related to some vs settings ( I have the same settings ! ) you have probably. It's minor just right click build the Windows project should build both or so.

The file in use issue is totally strange but I'm afraid it must be some shell explorer extension or anti-virus, anti-something you have on your side because just can't be reproduced.

**Comment by boriscallens** [comment]
Fixed it!
After installing the 32 bit version of the vs2013 redistributables and deleting all the existing binaries, it worked again. Thanks for helping me :)
