### ISSUE TITLE
Simple Terrain example won't compile for Windows 10 in release configuration.

### ISSUE THREAD

**Issue by tattries** [SiliconStudio/paradox#311]
Paradox Version 1.3.3.

error from VS 2015 is ...	Internal compiler error: Object reference not set to an instance of an object.		
.

**Comment by tattries** [comment]
Actually all samples have this problem in 1.3.3.

**Comment by jwollen** [comment]
Thanks for the report!
This might be a bug in the .NET Native compiler. We will work around it for the upcoming release.

You might also want to install "Tools for Universal Windows Apps 1.1" if you haven't already.
Let us know if you have any more problems.

**Comment by Gavin-Williams** [comment]
This doesn't seem fixed, I just reinstalled today. and the material shader sample doesn't work.

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: MaterialShader.Game, Configuration: Debug Windows10 ------
1>  Patch for assembly [MaterialShader.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
1>  MaterialShader.Game -> C:\Users\deads\OneDrive\Documents\Paradox Projects\MaterialShader\MaterialShader\Bin\Windows10\Debug\MaterialShader.Game.dll
2>------ Build started: Project: MaterialShader.Windows10, Configuration: Debug x64 ------
2>  Waiting 500ms for the proxy server to start and connect to it
2>  Unexpected exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileLoadException: The path is too long after being fully qualified.  Make sure the full path is less than 260 characters and the directory name is less than 248 characters.
2>     at SiliconStudio.DataSerializers.SiliconStudioAssetsCompilerAppSerializerFactory.Initialize()
2>     at .cctor()
2>     --- End of inner exception stack trace ---
2>     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2>     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2>     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2>     at SiliconStudio.ExecServer.AppDomainShadow.AssemblyLoaderCallback.Run()
2>     at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
2>     at SiliconStudio.ExecServer.AppDomainShadow.Run(String workingDirectory, String[] args, IServerLogger logger)
2>C:\Users\deads\AppData\Local\Programs\Silicon Studio\Paradox\GamePackages\Paradox.1.3.4-beta\Targets\Paradox.targets(219,5): error MSB3073: The command ""C:\Users\deads\AppData\Local\Programs\Silicon Studio\Paradox\GamePackages\Paradox.1.3.4-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerClient.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows10 --graphics-platform=Direct3D11 --profile=Windows10 --project-configuration=Debug --output-path="C:\Users\deads\OneDrive\Documents\Paradox Projects\MaterialShader\MaterialShader\Bin\Windows10-x64\Debug\data" --build-path="C:\Users\deads\OneDrive\Documents\Paradox Projects\MaterialShader\MaterialShader\MaterialShader.Windows10\..\obj\data" --package-file="C:\Users\deads\OneDrive\Documents\Paradox Projects\MaterialShader\MaterialShader\MaterialShader.Windows10\..\MaterialShader.pdxpkg" --log-pipe=""" exited with code 1.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by xen2** [comment]
System.IO.FileLoadException: The path is too long after being fully qualified. Make sure the full path is less than 260 characters and the directory name is less than 248 characters.

Looks like another issue, and I think we can't do much about this one (Windows path restriction); you probably need to create your project to a location with a smaller path (i.e. C:\DEV\MyProject instead of C:\Users\XXX\Paradox Projects\MyPath1\XXX)

**Comment by Gavin-Williams** [comment]
I read 124 characters ...

C:\Users\deads\OneDrive\Documents\Paradox Projects\MaterialShader\MaterialShader\Bin\Windows10\Debug\MaterialShader.Game.dll

And this is the default folder that Paradox selected.

**Comment by xen2** [comment]
Unfortunately Windows10 adds a lot of characters.
D:\Paradox Projects\MaterialShader\ should works though. Could be Paradox install dir and not the sample itself.

**Comment by xenux** [comment]
Initial issue have been fixed. So I close the issue.
For problems with installation path and path length, see issues #328 and #308.
