### ISSUE TITLE
Some Lights not showing in 1.3.3

### ISSUE THREAD

**Issue by wanderwurst** [SiliconStudio/paradox#312]
I create multiple lights in a row for a landing-strip-kind-of thing.
Depending on the camera position, lights seem to become visible and invisible again.
I managed to produce a simple test case:

Create a new project with 1.3.3, everything at default (on Windows 7, VS 2015, GTX660, all updated).
Remove the default sphere.

Add a point light, move it to X=-5 Y=0.2 Z=0 it should cast about half a circle on the left border of the ground. Color is White, Radius=1, Intensity=10

Move the camera away to a top down position to X=0 Y=20 Z=0, Rotation X=-90 (others zero).

Create two scripts:

```C#
using SiliconStudio.Paradox.Engine;

namespace LightTest
{
    public class CloneScript : SyncScript
    {
        public int CloneCount = 10;

        public Entity Reference = null;

        public override void Start()
        {
            base.Start();

            if (Reference != null)
            {
                for (int i = 0; i < CloneCount; i++)
                {
                    Entity clone = Reference.Clone();
                    SceneSystem.SceneInstance.Scene.AddChild(clone);
                    clone.Transform.Position.X += i + 1;
                }
            }
        }

        public override void Update()
        {
        }
    }
}
```

```C#
using SiliconStudio.Paradox.Engine;

namespace LightTest
{
    public class MoveScript : SyncScript
    {
        public float Speed = 0.1f;

        public override void Update()
        {
            if (Game.IsRunning)
            {
                if (Input.IsKeyDown(SiliconStudio.Paradox.Input.Keys.Left))
                {
                    Entity.Transform.Position.X -= Speed;
                }
                else if (Input.IsKeyDown(SiliconStudio.Paradox.Input.Keys.Right))
                {
                    Entity.Transform.Position.X += Speed;
                }
            }
        }
    }
}
```

In Paradox Studio, attach both scripts to the Camera.
Set the "Reference" for the CloneScript to be the PointLight.

Run.

You should be looking top down onto a light and it's 10 clones, but only 8 lights are displayed for me:

![start](https://cloud.githubusercontent.com/assets/14100936/10035008/1a65e674-6196-11e5-9890-c8924add7d4d.png)

If you press the left cursor key until lights leave the screen, other lights become visible. You can make them pop in and out of the scene.

![inout](https://cloud.githubusercontent.com/assets/14100936/10035046/555210e6-6196-11e5-90ba-c73af168719e.png)

Now I am perfectly aware that maybe I am just not supposed to be using that many lights in a scene. Is there an internal limit to how many lights can be shown at once? And if so, what would be a better approach to have up to maybe a hundred lights in a scene? (I tried emissive materials, but they just become brighter, they don't cast any light on their surroundings)

(Sorry for being a pest, but I am kinda clueless again)

**Comment by Toasterthegamer** [comment]
Since paradox is using forward rendering as of right now I think there is probably a maximum of 7-8 lights. I know that the roadmap says paradox is looking to move to forward plus rendering I think by the end of the year and then it should be able to support 1000's of lights. 

https://trello.com/c/8Stl1c46/12-forward-rendering

**Comment by wanderwurst** [comment]
Ah, ok. Thanks for your input. Googling around based on that I find the 8 light limit pretty much everywhere, not just Paradox. I had no idea.
Great to hear there are advanced implementations ahead. For now I guess I'll just try and replace things with additive sprites or something.
Thanks again.
