### ISSUE TITLE
Periods in file names cause paradox package compiler to fail in V1.3.3

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/paradox#313]
Paradox has issues with periods in file names. An example:

Vector.Extensions.cs

Paradox believes the file extension is .Extensions not .cs.

Paradox fails at line 353 in this file(I believe):
https://github.com/SiliconStudio/paradox/blob/bdce9a9f3bf721ba47fba25793f6256de8b3aa42/sources/assets/SiliconStudio.Assets/PackageAssetCollection.cs

**Comment by sinkingsugar** [comment]
Short answer: we're looking to shift this limitation :)

But scripts are now assets basically ( as far as the editor is concerned, they follow a different path when making the package of course tho.. aka compiled ) and so they follow assets rules for naming as well, which means no dots in names.

**Comment by sinkingsugar** [comment]
This issue is fixed in 1.3.4 version, please update and let us know if you have any further issue.
