### ISSUE TITLE
Error on Convert from 1.2 to 1.3

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#318]
Hi,
This bug is simple. I'm using files with names like this "BasicUI.xaml.cs". Convert fails, because It thinks it's XAML file, which is not.

[]: Error: Error while loading package [650dfdf3-e237-4050-9753-c4c4776b0a90]. System.ArgumentException: An asset [BasicUI_Paradox.Game/GeneratedUI/BasicUI.xaml] cannot be registered with an extension [.xaml]

I'm not able to load my project properly anymore. It fails every time on that error.

**Comment by Toasterthegamer** [comment]
I already reported the issue here:
#313

**Comment by EmptyKeys** [comment]
Ah I see, cool. So we can merge those two i guess. :)

**Comment by sinkingsugar** [comment]
I cannot reproduce with the last version.
This issue is fixed in 1.3.4 version, please update and let us know if you have any further issue.

**Comment by EmptyKeys** [comment]
yeah works with 1.3.4 ... closing
