### ISSUE TITLE
Resolution problem in Windows.

### ISSUE THREAD

**Issue by FuzsyDk** [SiliconStudio/paradox#324]
I tried change the resolution of my application by doing the following:
protected override void Initialize()
{
	GraphicsDeviceManager.PreferredBackBufferWidth = 320;
	GraphicsDeviceManager.PreferredBackBufferHeight = 280; 
	base.Initialize();
 }
I have also tried with different screen resolutions (1680 x 1050), but both with the same result:
Black screen and 2 fps.

**Comment by xenux** [comment]
Hi Fuzsy,

The application resolution as well as other application parameters have to be set from the editor in the game setting.
If you prefer setting them from the code, you can set the Game.AutoLoadDefaultSettings property to false. Note that doing this is not recommended as it ignores all the game settings set from the editor (default scene, graphic profile, screen size, color space, etc...). It that case all those parameters have to be set in the code or their default value will be used.

**Comment by xenux** [comment]
I close the issue. Feel free to reopen if there is still any problem.

**Comment by Kryptos-FR** [comment]
Isn't there a way to load all settings from the file and *then* only override some of them?

**Comment by FuzsyDk** [comment]
Hi Xenux,

Thank you for your answer.

I tried to change the resolution in editor, but could not find it. 
I saw tutorial video that showed how to set the resolution -> "Package Properties" for the Game as you also said. 
But as you can see in the attached image, the option is not available for me. Has the option been moved? Or shall I do something to make the resolution option available?

![resulation](https://cloud.githubusercontent.com/assets/15263844/10720072/5fd27224-7b93-11e5-84ff-968d8a1d68fa.jpg)


Thanks in advance.

**Comment by Kryptos-FR** [comment]
These settings are in the GameSettings asset that you can find at the package level (look in the Asset view).

**Comment by FuzsyDk** [comment]
Ah...! Found it.
Thank you Kryptos-FR
