### ISSUE TITLE
Unable to make the application go to fullscreen in Windows.

### ISSUE THREAD

**Issue by FuzsyDk** [SiliconStudio/paradox#325]
I tried to make the application go to fullscreen by doing the following:
protected override void Initialize()
{
	GraphicsDeviceManager.IsFullScreen = true;
	base.Initialize();
}
The screen goes black and nothing happens.

I also got the same issue, as issue #132 - Fullscreen switch doesn't work.

Is there any other way to make the application go fullscreen?

**Comment by FuzsyDk** [comment]
Something has change today. The fullscreen parameter still does not work, but I do not get a permanent black screen.

What I see today: 
It seems to be a timing problem. The error is only periodic. 

One of two scenarios happens:

1: The screen flashes black a couple of times and then shows the full screen image for a split second. Then it goes back to window size, but without borders.

2: The screen flashes black a couple of times and the shows the full screen image.

**Comment by Kryptos-FR** [comment]
What resolution did you set? Is this resolution supported by your graphic card/operating system?

**Comment by FuzsyDk** [comment]
I tested with the default resolution 1280 x 720 and with 1280 x 800 which is the correct aspect for my screen, but with the same result.

Both resolution is supported by Windows 7 and my graphic card:

My computer:
OS: Windows 7 Professional 64-bit SP1
CPU: Intel Core i7 4700MQ @ 2.40GHz
Graphic card: 2047MB NVIDIA GeForce GTX 765M
With 4 screens connected. 3 of them is active.

**Comment by Kryptos-FR** [comment]
Hum. I did a simple game example and it worked on my PC. Can you try with only one or two screens connected and see if you still have the issue?

**Comment by FuzsyDk** [comment]
I created a new project and… well… full screen worked. 

So the problem must be related to my application. I think the problem is that I got a WPF window that is launched on one of my other screen from the same application and it seems to interfere with the paradox game window in some way.

Thank you again Kryptos-FR. :-)
