### ISSUE TITLE
Issues with path length

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/paradox#328]
So following up on the issue with path being too long, preventing samples from running ..

1>------ Build started: Project: MaterialShader.Windows10, Configuration: Debug x64 ------
1>  Waiting 500ms for the proxy server to start and connect to it
1>  Unexpected exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileLoadException: The path is too long after being fully qualified.  Make sure the full path is less than 260 characters and the directory name is less than 248 characters.
1>     at SiliconStudio.DataSerializers.SiliconStudioAssetsCompilerAppSerializerFactory.Initialize()
1>     at .cctor()
1>     --- End of inner exception stack trace ---
1>     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
1>     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
1>     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>     at SiliconStudio.ExecServer.AppDomainShadow.AssemblyLoaderCallback.Run()
1>     at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
1>     at SiliconStudio.ExecServer.AppDomainShadow.Run(String workingDirectory, String[] args, IServerLogger logger)
1>C:\Users\deads\AppData\Local\Programs\Silicon Studio\Paradox\GamePackages\Paradox.1.3.4-beta\Targets\Paradox.targets(219,5): error MSB3073: The command ""C:\Users\deads\AppData\Local\Programs\Silicon Studio\Paradox\GamePackages\Paradox.1.3.4-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerClient.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows10 --graphics-platform=Direct3D11 --profile=Windows10 --project-configuration=Debug --output-path="D:\Paradox\MaterialShader\MaterialShader\Bin\Windows10-x64\Debug\data" --build-path="D:\Paradox\MaterialShader\MaterialShader\MaterialShader.Windows10\..\obj\data" --package-file="D:\Paradox\MaterialShader\MaterialShader\MaterialShader.Windows10\..\MaterialShader.pdxpkg" --log-pipe=""" exited with code 1.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

I don't see a way to change the install directory in the launcher, I just uninstalled Paradox and reinstalled it, and I wasn't presented with an option to change install directory.

**Comment by Gavin-Williams** [comment]
And is this the install directory ...  C:\Users\deads\AppData\Local\Programs\Silicon Studio\ ?

That's not the correct place to install an application to. It should be put into one of the 'program files' folders

**Comment by Gavin-Williams** [comment]
And after moving the paradox folder, Visual Studio now gives this error when it's launched ..

Error Initializing Paradox Language Service: System.IO.FileNotFoundException: Could not load file or assembly 'SiliconStudio.Paradox.VisualStudio.Commands' or one of its dependencies. The system cannot find the file specified.
File name: 'SiliconStudio.Paradox.VisualStudio.Commands'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at SiliconStudio.Paradox.VisualStudio.Commands.ParadoxCommandsProxy..ctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

And I did reinstall the VS plugin.

**Comment by xen2** [comment]
You probably have to manually fix the SiliconStudioParadoxDir environment variable.

**Comment by Gavin-Williams** [comment]
ah ok, thanks.

**Comment by xenux** [comment]
Installation path have been fixed in recent versions of paradox. So I close the issue. Thanks for the feedback.
