### ISSUE TITLE
[Suggestion] A BillboardComponent

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/paradox#57]
Hi,

I have been thinking about a BillboardComponent that would be a cool idea.  Something like:

    public class BillboardComponent: EntityComponent
    {
        /// <summary>
        /// The property key of this component.
        /// </summary>
        public static PropertyKey<BillboardComponent> Key = new PropertyKey<BillboardComponent>("Key", typeof(BillboardComponent));

        /// <summary>
        /// Size of billboard.  Not sure if this should be in world/view coordinates, maybe configurable.
        /// </summary>
        public Vector2 Size { get; set; }

        /// <summary>
        /// Offset from Entity Translation
        /// </summary>
        public Vector3 Offset { get; set; }

        public float Opacity { get; set; }

        public bool IsVisible { get; set; }

        public bool IsDepthTested { get; set; }

        /// <summary>
        /// If you just want a static image
        /// </summary>
        public ImageFragment Image { get; set; }

        /// <summary>
        /// If you want a more Complex billboard like stats for an RPG.  Probably don't make it clickable etc.
        /// </summary>
        public UIElement UIElement { get; set; }

        /// <summary>
        /// Maybe a animated sprite???
        /// </summary>
        public SpriteGroup Sprite { get; set; }

        public override PropertyKey DefaultKey
        {
            get { return Key; }
        }
    }

Or perhaps it would be better with 3 separate components for image, UIElement and sprite. Do you think this idea is worth pursuing?  

I realize it would require a renderer and perhaps a processor of some sort to keep the sprite/UIElement updated. I haven't really worked out how the engine all ties together yet.

Cheers,
dfkeenan

**Comment by Benlitz** [comment]
The SpriteComponent now supports billboards
