### ISSUE TITLE
In-scene prefab's lights don't render correctly

### ISSUE THREAD

**Issue by ghost** [SiliconStudio/paradox#586]
In the prefab editor I added two lights. It looks like this:
<img width="966" alt="2017-05-12 1" src="https://cloud.githubusercontent.com/assets/17237506/26001344/574bbda8-372c-11e7-8338-51c7772c098b.png">

I saved everything, and even restarted Game Studio. But the changes don't fully take place. All four light icons are there. But only one light renders. In-scene, the prefabs look like this:
<img width="1055" alt="2017-05-12" src="https://cloud.githubusercontent.com/assets/17237506/26001346/57548d66-372c-11e7-8d9d-fc2bd2f64c5e.png">

I found that if I select any of the other lights, in scene hierarchy, and disable them. Then the one light that renders correctly. It stops casting light.

**Comment by ghost** [comment]
If I disable point shadow map, on a light that is not casting any light. Then the light that renders normally (far left), stops casting light. And the light which I turned off point shadows on. It starts to cast light.

I disabled all point shadow maps on the two lights in the prefab editor. But that didn't resolve the problem. In-scene, still only the far left light renders. All those issues are in the built game, too, by the way.

**Comment by ghost** [comment]
I deleted both light components on the entities. And re-added them. Result was that all right lights rendered, but all left lights didn't. I closed Game Studio, and re-opened. Then it look just like before. The far left light rendered, and all other didn't. Even disabling the shadow maps caused the same behavior, as described in the post above this one.

**Comment by ghost** [comment]
What does this green marked number mean? Is it the ID for the serialized data? I suspect that all four lights do render, but all at the same location.

<img width="677" alt="2017-05-12 2" src="https://cloud.githubusercontent.com/assets/17237506/26003366/c884adf8-3732-11e7-82fb-e97d80d879ab.png">

Sadly I forgot with light it was, the right or the left. However, inside the prefab file, the Z position wasn't zero like it should be. I set it to zero, though this didn't fix anything. But if the serializer accesses the wrong data set, then it wouldn't make a difference anyways..

**Comment by ghost** [comment]
Removing the prefabs from the scene. And adding them again. Is not fixing the problem. I even ended up having the Assembly Bay with the only light correctly rendering, that was previously on the right side, ending up on the left side.

Seems I can't reproduce the problem with a new Xenko 2.0 project. The scene file is clean when I delete the prefabs. However, I can reproduce the problem with in my current project. I created a new prefab. And then added only one arm with a red light. on the bay ground. I added this prefab to the scene. And even the single light doesn't render at all. 

When I add a fourth instance of that prefab. The light of the fourth, and the lights of any more prefab instance I add to the scene, but DO work. Though, when I delete the first prefab instance I added. The light of the fourth prefab in scene, turns itself off. And when I continue to delete the second prefab, the light of the fifth prefab goes out, too. And so on.

Maybe it's not the serializer. But the DX11 renderer. I use a GTX 970.

However, regarding the serializer. When I crated the new prefab. I was able to spot the Z position bug again, which I mentioned earlier. The prefab editor, and the scene show 0 in the property panel. But in the file, Z position is set to -1.7359166E-08. I set it to the intended 0.0. But it didn't solve the rendering problem. And from then on, the values always matched those of the property panel. Seems this glitch snapped out of its issue.
<img width="988" alt="2017-05-15 1" src="https://cloud.githubusercontent.com/assets/17237506/26059342/bd415224-3981-11e7-8e9e-84724d0f05ac.png">

**Comment by ghost** [comment]
Yeah, I'm 100% certain now. That it's the renderer, and not the prefabs or the serializer.

When I move the camera around, and even only when moving a bit closer or further away from the lights. They disappear or light up again. When I switch between Linear and Gamma, camera doesn't have to move either. The lights turn on. Though they don't stay on.

I'm using GTX 970. The drives are up to date. This problem is with DX10, 11, and with Gamma and Linear settings. DX9 doesn't build at all. Built game shows the same problems. Note that I didn't change anything in the graphics composer. I started with a fresh 2.0 Xenko project.

**Comment by ghost** [comment]
Note that you may need a lot of lights in the scene(~10 ligts ). In order to make the turn on and off by moving the camera closer or further away. That's why I didn't notice this as a mere render issue earlier.

**Comment by ghost** [comment]
I was able to narrow down the problem further. It's the Point Shadow Map that messes up every light with that setting on. So, in prefab editor. All renders as expected. But even if the lights render in scene, they don't cast a shadow.

That's why the blue light of the combat rig, always rendered fine. It doesn't cast any shadows.

**Comment by ghost** [comment]
The same problems are on a GTX 1080.

**Comment by Benlitz** [comment]
Hi,

Good catch, there was indeed an issue with shadow maps for point lights. This issue has been fixed internally and the fix will be available in the next release.
