### ISSUE TITLE
Possible null pointer dereference

### ISSUE THREAD

**Issue by AppChecker** [SiliconStudio/paradox#594]
Hi

Please look [this code fragment](https://git.xenko.com/xenko/Xenko-Runtime/blob/b46be65d826accd9458de960553d289f70106935/sources/common/shaders/Irony/Parsing/Grammar/Grammar.cs#L206):
`        return (node.State != null ? string.Empty : "(State " + node.State.Name + ")"); `
if node.State is null  'node.State.Name' will be executed.
Probably, it should be
`        return (node.State == null ? string.Empty : "(State " + node.State.Name + ")"); `

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php).

**Comment by Benlitz** [comment]
Hi,

We fixed this issue internally, although I don't believe we're even using this code path in Xenko. The problem originates in Irony, a grammar parser that we forked:
https://irony.codeplex.com/SourceControl/latest#Irony/Parsing/Grammar/Grammar.cs
