### ISSUE TITLE
Transform position and rotation issue

### ISSUE THREAD

**Issue by THEN3LLI** [SiliconStudio/paradox#609]
Hey guys,
programming with Xenko 2.0 I found issues relative to the update of the axis.
Rotating an Entity, axis should rotate with it right? This not happen when i use this code:
`Entity.Transform.Rotation = Quaternion.RotationAxis(c, angle);
Entity.Transform.Position += new Vector3(0,0,-0.01f);`
Anyone knows how fix this problem? 
Thanks in advance 💃

**Comment by Kryptos-FR** [comment]
Hello @THEN3LLI thanks for your interest in Xenko.

For questions relative to how to use the engine, please use the [QA website](http://answers.xenko.com) or the [forums](https://forums.xenko.com/). The issues on GitHub are dedicated to bugs and feature suggestions.

Thanks
