### ISSUE TITLE
FPS counter doesn't work

### ISSUE THREAD

**Issue by katsutoshi-hayashida** [SiliconStudio/paradox#618]
I added this code at somewhere.
```csharp
Profiler.Enable(GameProfilingKeys.GameDrawFPS);
```
But nothing happened.

Game Studio 2.0.4.1
Windows 10/Windows 7/Ubuntu 16.04
DirectX 10, DirectX 11.0, OpenGL, Vulkan

**Comment by Kryptos-FR** [comment]
To enable or disable the profiler at runtime you need to call (from a script):

```csharp
var game = (Game)Game;
game.ProfilerSystem.EnableProfiling();
// or
game.ProfilerSystem.DisableProfiling();
```

For convenience we provide a `GameProfiler` script template (available from the add asset menu in the Game Studio). With the script you can enable/disable the profiler by pressing CTRL+SHIFT+P.

**Comment by katsutoshi-hayashida** [comment]
Thank you, Kryptos. It works.

**Comment by Kryptos-FR** [comment]
No problem. The profiling will be improved in `2.1` and will have its own documentation.
