### ISSUE TITLE
Upgrading 2.0 to 2.1 failed

### ISSUE THREAD

**Issue by katsutoshi-hayashida** [SiliconStudio/paradox#621]
I upgraded my project from 2.0 to 2.1 and got bunch of errors.
I noticed that all prefabs have "ref!!" in RootParts.

For example:

2.0

    !PrefabAsset
    Id: 7acdd903-9e44-4267-95e4-14ada033de9c
    SerializedVersion: {Xenko: 2.0.0.0}
    Tags: []
    Hierarchy:
        RootPartIds:
            - 822f9632-cf35-4a60-a46c-5a1f037a8111
        Parts:
            -   Entity:
                    Id: 822f9632-cf35-4a

2.1

    !PrefabAsset
    Id: 7acdd903-9e44-4267-95e4-14ada033de9c
    SerializedVersion: {Xenko: 2.1.0.1}
    Tags: []
    Hierarchy:
        RootParts:
            - ref!! 822f9632-cf35-4a60-a46c-5a1f037a8111
        Parts:
            -   Entity:
                    Id: 822f9632-cf35-4a60-a46c-5a1f037a8111

Main Scene and UI page have the same/similer errors.

Main Scene

	!SceneAsset
	Id: 2ac455c2-f55f-4080-9d80-d652ba67c030
	SerializedVersion: {Xenko: 2.1.0.1}
	Tags: []
	ChildrenIds: []
	Offset: {X: 0.0, Y: 0.0, Z: 0.0}
	Hierarchy:
	    RootParts:
	        - ref!! 475fa770-eb3f-4b0e-b859-13f7ec4c622f
	        - ref!! 0db953ea-a4b5-4fc1-9986-40d443d4b6f5
	        - ref!! 564de2b5-11ce-4f9d-9a89-43e09063967e
	        - ref!! 2979edca-1939-47a3-9a88-97ca06b79ed4

UI Page

	!UIPageAsset
	Id: e8e99e3f-1f18-410d-971e-c46f8f7a7fc6
	SerializedVersion: {Xenko: 2.1.0.1}
	Tags: []
	Design:
	    Resolution: {X: 3840.0, Y: 2160.0, Z: 1000.0}
	Hierarchy:
	    RootParts:
	        - !Grid ref!! 3a9c01f7-a4d3-4230-9cb3-562c0e6a5ccc

I experimentally removed "reff!!" with a text editor but the game is not buildable.
Apparently RootPartsIds is renamed to RootParts but it is not mentioned in the release note.
http://doc.xenko.com/latest/en/ReleaseNotes/ReleaseNotes.html

**Comment by katsutoshi-hayashida** [comment]
This report was false. I am able to build my game collecting some errors.

**Comment by Kryptos-FR** [comment]
From the release notes:

> Changed how root parts of hierarchical assets (prefab, scene, UI) are referenced and serialized (direct references instead of Guids)
