### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by Eteokles** [SiliconStudio/paradox#654]
When I try to create a new project I have this error. Visual studio and Xenko fresh installed. Last version for both of them.

`Verbose: Loading Assets from Package [Xenko.xkpkg]

Verbose: Loading Assets from Package [MyGame.xkpkg] 
Verbose: Generating MyGame.Game... 
Verbose: Generating MyGame.Windows... 
Verbose: Loading Assets from Package [MyGame.xkpkg] 
Verbose: Compiling game assemblies... 
Verbose: Restoring packages for D:\Xenko Projects\MyGame\MyGame\MyGame.Game\project.json... 
Verbose: Committing restore... 
Verbose: Writing lock file to disk. Path: D:\Xenko  Projects\MyGame\MyGame\MyGame.Game\project.lock.json 
Verbose: D:\Xenko Projects\MyGame\MyGame\MyGame.Game\project.json 
Verbose: Restore completed in 633ms. 
Verbose: NuGet Config files used: 
Verbose:     C:\Users\girot\AppData\Roaming\NuGet\NuGet.Config 
Verbose: Feeds used: 
Verbose:     https://api.nuget.org/v3/index.json 
[C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0 \Bin\Microsoft.Common.CurrentVersion.targets(2090,9)]: Error:  The "FindDependenciesOfExternallyResolvedReferences" parameter is not supported by  the "ResolveAssemblyReference" task. Verify the parameter exists on the task, and it is a settable public instance property. 
[C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5)]: Error: The "ResolveAssemblyReference" task could not be initialized with its input parameters.  
Error: Unable to build assembly reference [D:\Xenko  Projects\MyGame\MyGame\Bin\Windows\Debug\MyGame.Game.dll] 
Verbose: Game assemblies compiled... 
Warning: Can't load Game assembly 
Verbose: Compiling game assemblies... 
Verbose: Game assemblies compiled... 
Verbose: Restoring NuGet packages... 
Verbose: Restoring packages for D:\Xenko Projects\MyGame\MyGame\MyGame.Windows\project.json...
Verbose: Committing restore... 
Verbose: Writing lock file to disk. Path: D:\Xenko  Projects\MyGame\MyGame\MyGame.Windows\project.lock.json 
Verbose: D:\Xenko Projects\MyGame\MyGame\MyGame.Windows\project.json 
Verbose: Restore completed in 642ms. 
Verbose: NuGet Config files used: 
Verbose:     C:\Users\girot\AppData\Roaming\NuGet\NuGet.Config 
Verbose: Feeds used: 
Verbose:     https://api.nuget.org/v3/index.json 
`

**Comment by xen2** [comment]
This was due to incompatibility between MSBuild we embed and VS one (it happens when VS is updated to latest version).

Hopefully 2.1.2 should fix this issue (at least temporarily, we are working on a better long term fix to stay compatible with all future versions of VS).
