### ISSUE TITLE
RequireComponentAttribute unuseable

### ISSUE THREAD

**Issue by stefnotch** [SiliconStudio/paradox#661]
@xen2 Why can't I use [RequireComponentAttribute](https://github.com/SiliconStudio/xenko/blob/master-2.1/sources/engine/SiliconStudio.Xenko.Engine/Engine/RequireComponentAttribute.cs)? 
It says:
```text
CS0246	The type or namespace name 'RequireComponentAttribute' could not be found (are you missing a using directive or an assembly reference?)
```

Code:
```cs
var x = typeof(RequireComponentAttribute);
```

However, [AllowMultipleComponentsAttribute](https://github.com/SiliconStudio/xenko/blob/6fca455a2d67f6f53fc1c7ad8c3722938b3b9a56/sources/engine/SiliconStudio.Xenko.Engine/Engine/AllowMultipleComponentsAttribute.cs) works. Both of them are in the same namespace and are supposed to be in the same .dll.

One slightly interesting thing is that the [RequireComponentAttribute doesn't seem to get used anywhere.](https://github.com/SiliconStudio/xenko/search?utf8=%E2%9C%93&q=RequireComponentAttribute&type=)

**Comment by stefnotch** [comment]
![image](https://user-images.githubusercontent.com/10220080/38326575-696eaa56-3846-11e8-83aa-0a9db71df7b4.png)

Apparently, it's missing from the .dll.

**Comment by xen2** [comment]
Not part of the C# project file. Looks like a file that should have been erased.

**Comment by stefnotch** [comment]
@xen2 Oh, that explains a lot. Though, it seems like a rather convenient attribute. My use case would be something like this:
Force the user to add a camera component to the player entity:
```cs
[RequireComponentAttribute(typeof(CameraComponent))]
public class Player: SyncScript
{
    private CameraComponent _camera;
    public void Start() {
         _camera = this.Entity.Get<CameraComponent>();
    }
}
```
        
      
Though, after thinking about it for a while, it would probably be more elegant to use `[NotNull]` to force the user to add a camera component
```cs
public class Player: SyncScript
{
    //Game Studio doesn't seem to check this, which makes it rather useless
    [NotNull]
    public CameraComponent Camera { get; set; }
}
```

https://github.com/SiliconStudio/xenko/issues/662
