### ISSUE TITLE
Corrupted Project

### ISSUE THREAD

**Issue by stefnotch** [SiliconStudio/paradox#663]
When a property like this gets changed in the game studio, the project (or scene?) will get corrupted. And, to make matters worse, the user will only notice the corruption upon opening and closing the project.

```cs
public class Test: ScriptComponent {
	private bool n = false;
	public bool test
	{
		get
		{
			return n;
		}
		set
		{
			if (Entity != null)
			{
				n = true;
                                //This is the cause of the corruption
				Entity.GetOrCreate<RigidbodyComponent>();
			}
		}
	}
}
```

(I was able to fix mine by undoing the changes to the .xkscene file)

**Comment by Kryptos-FR** [comment]
Properties that are serializable (i.e. editable in the GameStudio) should not have a side-effect.
I remember trying to prevent that kind of behavior but couldn't find a solution.

There is an explicit warning in the documentation: http://doc.xenko.com/latest/en/manual/scripts/public-properties-and-fields.html#add-a-public-property-or-field
