### ISSUE TITLE
Game crashes on startup because it can't connect to Xenko connection router

### ISSUE THREAD

**Issue by tebjan** [SiliconStudio/paradox#668]
This happens almost on every start on my machine with Windows 10 64 bit. When closing the exception window, the game closes as well.

**Comment by stefnotch** [comment]
Did you check your firewall settings? (Try disabling it)

**Comment by stefnotch** [comment]
https://forums.xenko.com/t/routerclient-cs-is-throwing-an-exception/724

**Comment by tebjan** [comment]
yes, that's it! thanks @stefnotch
