### ISSUE TITLE
Missing cleanup on uninstall

### ISSUE THREAD

**Issue by Hammerstad** [SiliconStudio/paradox#678]
After uninstalling Xenko, my development environment was left in some form of limbo. I had to manually clean the following things in order for everything to work properly:

 - Remove the Xenko extension from visual studio.
 - Remove xenko and xenko-dev feed from global nuget.config.

Please add these steps to your uninstall procedure.

**Comment by Kryptos-FR** [comment]
Hi @Hammerstad. Thanks for the feedback.

Since Xenko went MIT, new issues should be posted to [xenko3d/xenko](https://github.com/xenko3d/xenko/issues).

**Comment by Hammerstad** [comment]
Ok, thanks. Will post there :)
