### ISSUE TITLE
Android: Need x86 native libraries to properly run in emulators (i.e. Xamarin Android Player)

### ISSUE THREAD

**Issue by gitfool** [SiliconStudio/paradox#82]
* Install [Xamarin Android Player](http://developer.xamarin.com/guides/android/getting_started/installation/android-player/) for Windows (Preview 0.0.24)
 * ... including upgrade to latest [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (4.3.18)
* Build and then try to deploy, e.g. Custom Effect sample, to Android Player
* Results in the following error:

> [CustomEffectGame]: Error: Unexpected exception. System.DllNotFoundException: libcore.dll

[DeployLog.txt.zip | uploaded via ZenHub](https://files.zenhub.io/5456d27609690c523ac990df)

Note: I'm using a custom build of Paradox, primarily for the better debugging experience, in case that makes a difference.

**Comment by xenux** [comment]
Hi, x86 support for native libraries have been added a while ago on Android.
But OpenGl ES2 emulator implementations seems several important flaws and we need quite some work on the engine side to adapt to those imperfections. By consequent the engine is still not working properly on emulators. We will try to make it for the non beta release but can't promise anything.
