### ISSUE TITLE
GameStudio texture compilation fails when Generate mip-maps is true in property grid.

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/paradox#92]
When compiling textures for a DX11.1 game, GameStudio incorrectly reports errors, stating that DX9.x doesn't support mip-maps of non-2 power. This may be true of DX9, but the device is being created with DX11.1 in code.

To resolve the issue, I set generate mipmaps to false in the property grid.

**Comment by Benlitz** [comment]
The feature level can now be modified in the package properties (version 1.1.0β)
